### ISSUE TITLE
Pull request/all checks have failed

### ISSUE THREAD

**Issue by anaalta** [makersacademy/problem-solving#10]
My situation is as follows: I somehow managed to work on a repo that was not forked from makers, in the end I did a new repo and pushed my local repo into it (with everything committed at once). For some reason, I have two extra jail.txt files: jail.txt.swo and jail.txt.swp (these were hidden). Which I understand has to do with the fact that I tried to edit the file in vi. In the process, I have learnt that the :q command to exit the editor does not always work. So I gave up and typed myself into jail.txt. But at pull request, I get "all checks fail" (apparently because of the two vi files). I delete them , pull requested again, failure. 
Here's what the details of the failed check look like:
https://www.dropbox.com/s/k3fv3ahfqmhp2ex/Screenshot%202017-03-20%2012.46.51.png?dl=0

The one in red, which I am assuming causes trouble, is:  

> The command _"find ./ -name "jail.txt" | xargs less | $(command -v md5 || command -v md5sum) | grep -qif /dev/stdin encoded" exited with 1._

Any ideas?

Thanks,

Ana

**Comment by motri** [comment]
Hi Ana! May I ask how you typed the name in jail.txt? I'm asking because I think I got a similar error (at least I think I did), and I solved it by removing the space between the first name and surname.

**Comment by FiddlersCode** [comment]
Try removing the inverted commas from "jail.txt" - so it becomes `-name jail.txt`

Also, you can screenshot and paste directly into the GitHub write window! :)

**Comment by anaalta** [comment]
@motri :) thanks, it did not solve it. But you were right, I did keep the space between the names. 
@pmuldoon the inverted commas command were on the details of my failed check, not something I did...

**Comment by FiddlersCode** [comment]
Line 143?

**Comment by anaalta** [comment]
yup, that entire photo is the detail of my check, not my terminal

**Comment by BertZZ** [comment]
If you find a solution let me know, I'm getting the exact same error and have no idea how to fix it

**Comment by nikeshashar** [comment]
Are we good with this now? If it's solved - let's close the issue

**Comment by anaalta** [comment]
yes, all good, closed now! Thank you all for the hints!
