### ISSUE TITLE
Rake Issue

### ISSUE THREAD

**Issue by alessiobortone2** [makersacademy/problem-solving#101]
Hi guys,  

I am going through the challenges, but when it comes to checking with rake I get this:

rake aborted!
Gem::MissingSpecError: Could not find 'rspec' (~> 3.0) among 23 total gem(s)
Checked in 'GEM_PATH=/Users/alessiobortone/.rvm/gems/ruby-2.4.0:/Users/alessiobortone/.rvm/gems/ruby-2.4.0@global', execute `gem env` for more information
/Users/alessiobortone/Documents/GitHub/ruby-kickstart/Rakefile:1:in `<top (required)>'
/Users/alessiobortone/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/alessiobortone/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/alessiobortone/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

However, I did install rake - not sure what I am doing wrong. Can I ask for your help? 
Thanks !!

Alessio

**Comment by david-div** [comment]
Hi Alesesio,

Sounds like the same issue I had: 
https://github.com/makersacademy/problem-solving/issues/99

I did the follow albeit on could 9.:

in Cloud9 you can install the rspec 3.0 by typing:
gem install rspec -v 3.0

After that for sure it will give you something like that:

Could not find proper version of rspec-core (3.1.7) in any of the sources
Run `bundle install` to install missing gems.

So you can run:

bundle install
rspec-core



Hope this helps.

David

**Comment by alessiobortone2** [comment]
Hi David, thanks so much for your help!
After installing rspec v3.0 (all ok until that point), I try bundle install and I get:
-bash: bundle: command not found 

What am I doing wrong? 

I also noticed that if I try to Rake 1:1 again, I now get a different error: 

rake aborted!
LoadError: cannot load such file -- bundler/gem_tasks
/Users/alessiobortone/Library/Mobile Documents/com~apple~CloudDocs/.Trash/rake/Rakefile:12:in `<top (required)>'
/Users/alessiobortone/.rvm/gems/ruby-2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/alessiobortone/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/alessiobortone/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

At least I get a different error, so I am progressing thanks to your help :) 

Thanks in advance ! 

Alessio

**Comment by alessiobortone2** [comment]
I managed to bundle install and now I am a step further. This is what I am getting atm: 
rake aborted!
Don't know how to build task '1:1' (see --tasks)
/Users/alessiobortone/Library/Mobile Documents/com~apple~CloudDocs/.Trash/rake/exe/rake:27:in `<top (required)>'
/Users/alessiobortone/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/alessiobortone/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by neoeno** [comment]
Hi Alessio!

Could you add the following:

* The code, or a link to your github repository where you get this error
* A screenshot of this error, including all the context around it (e.g. what you ran, etc)

Having the error messages is a great first step — the more comprehensive the information, the more accurate and comprehensive the diagnosis can be.

**Comment by alessiobortone2** [comment]
Thanks Kay! 

So, I have rspec installed in root and rake installed in my local ruby-kickstart directory. 
path: alessiobortone\Documents\Github\ruby-kickstart\rake

When I type "gem list" I can see I have this: 

bigdecimal (default: 1.3.0)
bundler (1.15.1)
bundler-unload (1.0.2)
coderay (1.1.1)
coveralls (0.8.21)
did_you_mean (1.1.0)
diff-lcs (1.3)
docile (1.1.5)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
io-console (default: 0.4.6)
json (2.1.0, default: 2.0.2)
method_source (0.8.2)
minitest (5.10.2, 5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.2)
power_assert (0.4.1)
pry (0.10.4)
psych (default: 2.2.2)
rake (12.0.0, 10.4.2)
rdoc (5.1.0, default: 5.0.0)
rspec (3.6.0, 3.0.0)
rspec-core (3.6.0, 3.0.4)
rspec-expectations (3.6.0, 3.0.4)
rspec-mocks (3.6.0, 3.0.4)
rspec-support (3.6.0, 3.0.4)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
simplecov (0.14.1)
simplecov-html (0.10.1)
slop (3.6.0)
term-ansicolor (1.6.0)
test-unit (3.2.3)
thor (0.19.4)
tins (1.15.0)
xmlrpc (0.2.1)

so I can see I have both rake and rspec available. 
But when I run rake 1:1, as per here: 

Alessios-MacBook-Air:rake alessiobortone$ rake 1:1

I get this: 

rake aborted!
Don't know how to build task '1:1' (see --tasks)
/Users/alessiobortone/Documents/GitHub/ruby-kickstart/rake/exe/rake:27:in `<top (required)>'
/Users/alessiobortone/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/alessiobortone/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

This is the furthest I got at the moment. Thanks in advance for your recommendations :)

**Comment by neoeno** [comment]
Thanks Alessio! While not a screenshot, this is still useful information.

Could you add:

* The code, or a link to your github repository where you get this error

**Comment by alessiobortone2** [comment]
Thanks Kay and David for helping, problem sorted !
