### ISSUE TITLE
Week 3 Step8.7: Unable to assign default value in hash

### ISSUE THREAD

**Issue by jenniferbacon01** [makersacademy/problem-solving#102]
Hi, hoping someone can help with this - I need the cohort to default to :november if the user doesn't enter a cohort. I've tried 3 solutions but none seem to work! Anyone have any ideas? Thanks :-)
![screen shot 2017-07-17 at 13 13 36](https://user-images.githubusercontent.com/28692326/28267409-ddc2d5c6-6af1-11e7-805a-d62cecc49c15.png)
![screen shot 2017-07-17 at 13 19 53](https://user-images.githubusercontent.com/28692326/28267608-b2a98852-6af2-11e7-9149-455086779ea5.png)
![screen shot 2017-07-17 at 13 21 14](https://user-images.githubusercontent.com/28692326/28267645-e077a6c4-6af2-11e7-8fbc-61191e8077e6.png)

**Comment by neoeno** [comment]
Hi Jennifer!

Run these examples in IRB one by one, taking note of the output, and let me know if it helps:

```ruby
# Example 1
cohort = gets # Then type in 'hi' and hit return

# Example 2
cohort = gets # Then just hit return

# Example 3
cohort = gets.gsub(/\n/, "") # Then just hit return

# Example 4
cohort = gets.gsub(/\n/, "").to_sym # Then just hit return

# Example 5
cohort = gets.gsub(/\n/, "").to_sym # Then just hit return
cohort == ""
```

**Comment by jenniferbacon01** [comment]
Ah thank you! I was stuck on this for so long!
