### ISSUE TITLE
PreCourse Week 4- Passing the first test no method error

### ISSUE THREAD

**Issue by ofrost617** [makersacademy/problem-solving#103]
I got the error message 'wrong number of arguments (1 for 0), then run RSpec having defined fizzbuzz to pass the test, but I keep getting the error 'undefined method 'to' for fizz string and can't work out where I'm going wrong, both me and my pairing partner are getting the same error.

Screenshots attached, thanks!

![screen shot 2017-07-25 at 13 54 05](https://user-images.githubusercontent.com/28751330/28572980-edc76c16-7140-11e7-87ed-51e8559e7b56.png)
![screen shot 2017-07-25 at 13 54 13](https://user-images.githubusercontent.com/28751330/28572982-efb68a0c-7140-11e7-8e66-49979d09fc27.png)
![screen shot 2017-07-25 at 13 54 28](https://user-images.githubusercontent.com/28751330/28573000-f7ad5f2e-7140-11e7-88c9-24b0bcf76fe0.png)

**Comment by stephengeller** [comment]
Try removing the whitespace between expect and (fizzbuzz...) in your spec, think I had a similar issue!
