### ISSUE TITLE
permission denied while trying to test ssh connection

### ISSUE THREAD

**Issue by leila3103** [makersacademy/problem-solving#108]
i 've tried to test my ssh connection but no luck , i got the fingerprint SSH keys associated with my account. Here the screen :
git remote -v
origin	git@github.com:makersacademy?playing-with-git.git (fetch)
origin	git@github.com:makersacademy?playing-with-git.git (push)
Leilas-MacBook-Pro:~ leila$ cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:makersacademy?playing-with-git.git
	fetch = +refs/heads/*:refs/remotes/origin/*
Leilas-MacBook-Pro:~ leila$ git push -u origin master
error: src refspec master does not match any.
error: failed to push some refs to 'git@github.com:makersacademy?playing-with-git.git'
Leilas-MacBook-Pro:~ leila$ git remote -v
origin	git@github.com:makersacademy?playing-with-git.git (fetch)
origin	git@github.com:makersacademy?playing-with-git.git (push)
Leilas-MacBook-Pro:~ leila$ git remote add origin git@github.com:makersacademy/playing-with-git.git
fatal: remote origin already exists.

any ideas what the problem?

**Comment by gijoeuk** [comment]
Hi Leila, I am having the same issue now. Did you get this resolved?

**Comment by leila3103** [comment]
No i didn't but i feel like the problem is linked with the ssh keys for GitHub. For some reason  my SSH connection isn't working but check this steps it might work for you :https://help.github.com/articles/connecting-to-github-with-ssh/
let me know if this works for you.
