### ISSUE TITLE
Syntax problem using ranges with && operator 'ruby-kickstart session 4_logic.rb'

### ISSUE THREAD

**Issue by JessicaBarclay** [makersacademy/problem-solving#11]
Can anyone see what I might be doing wrong on lines 15 and 16 in the screenshot? 
`nil` is being returned and I am not sure why...
(note: parenthesis don't seem to work, see line 16)

Also, I am sure there is a better way to write this but would really like understand how to resolve this particular function as I am so close!
Thanks in advance :)

![screen shot 2017-03-20 at 12 38 43](https://cloud.githubusercontent.com/assets/20893719/24100194/f2620464-0d6a-11e7-9057-c91f05ceceeb.png)
!

def grade(num_books, reads_books)
	if num_books < 10 && !reads_books ; "D"
	elsif num_books < 10 && reads_books ; "C"
	elsif num_books == 10...20 && !reads_books ; "C"
	elsif num_books == (10...20) && reads_books ; "B"
	elsif num_books >= 20 && !reads_books ; "B"
	elsif num_books >= 20 && reads_books ; "A"
  end
end

# My results:
p grade(4, false) # => "D"
p grade(4, true) # => "C"
p grade(15, true) # => nil
p grade(15, false) # => nil
p grade(22, true) # => "A"
p grade(20, false) # => "B"

**Comment by FiddlersCode** [comment]
Is it maybe that you have `==` instead of`=`?  This is always a tricky one for me to remember!

**Comment by JessicaBarclay** [comment]
@pmuldoon86 No I did try that, resulted in `grade': bad value for range (ArgumentError)`
Yes very frustrating! I am sure it is quite simple but I can't seem to see it
Thank you

**Comment by FiddlersCode** [comment]
I don't think it would stop your code, but shouldn't it be `10..20` not `10...20` so the range is inclusive? https://ruby-doc.org/core-2.2.0/Range.html

**Comment by TimRobinson1** [comment]
Have you tried searching in the range using the 'include?' method? :)

For example, using "(10..20).include?(num_books)"  instead of  "num_books == 10..20"

As I understand it, "num_books == 10..20" is trying to determine if the num_books integer is equal to a range, rather than searching for the number inside it, which is why it's producing nil, because it can't verify that the integer actually equals the range.  I hope that makes sense!  Let me know if I've done a terrible job explaining and I'll try again. 😄

**Comment by JessicaBarclay** [comment]
@pmuldoon86 I did think that but the final instruction starts at 20? So I wasn't sure if it should be inclusive or exclusive... but as you said it doesn't resolve it either

**Comment by FiddlersCode** [comment]
Tim's comment makes a lot of sense!!

**Comment by JessicaBarclay** [comment]
@TimRobinson1  Yes thats the one! That makes total sense, thank you!
![screen shot 2017-03-20 at 13 07 53](https://cloud.githubusercontent.com/assets/20893719/24100991/65cf2370-0d6e-11e7-8f46-01861cc9eb2d.png)

**Comment by JessicaBarclay** [comment]
Apologies I tagged @startuprob instead of @TimRobinson1 
*facepalm*
