### ISSUE TITLE
What does rm-rf mean? 

### ISSUE THREAD

**Issue by TomSpencerLondon** [makersacademy/problem-solving#110]
I know that rm means remove but not sure what rm-rf means.

**Comment by andyrow123** [comment]
As far as I'm aware -r is recursive and -f is force so chained together would be recursive force. This would delete write-protected files also without prompting.

**Comment by TomSpencerLondon** [comment]
Thank you Austin. In the Learn Python the Hard Way appendix A (exercise 14 Remove a File rm) newplace is a copied directory from something. This seems to mean that rm -rf newplace means recursively remove (or delete) all the files in the directory newplace.

**Comment by andyrow123** [comment]
Yes but more importantly, don't prompt for any confirmation when deleting write-protected files in the directory and directories within newplace. It could be dangerous unless you are sure you wanted to delete all the files in the directories.
