### ISSUE TITLE
'1 failing test'  in pull request reporting progressto Chief

### ISSUE THREAD

**Issue by oliverpople** [makersacademy/problem-solving#112]
Hi Guys, to finish step 6 in the challenge I sent a pull request to makersacademy/clmystery.   Here is the link to that pull request:  

https://github.com/makersacademy/clmystery/pull/669

It's says that 'All checks have failed:  1 failing check'.   Further details to the failed check can be found at:   

https://travis-ci.org/makersacademy/clmystery/builds/271142595?utm_source=github_status&utm_medium=notification

Anyone idea where i've gone wrong here? Thanks

**Comment by haletothewood** [comment]
It might be because your possible_witnesses.txt file is empty?

**Comment by haletothewood** [comment]
You also don't seem to have a suspects.txt file which is the step before submitting a pull request in step6.

**Comment by haletothewood** [comment]
Also, just realised I think the final check only works once you've completed step9. The pull request will fail until then. I think.
