### ISSUE TITLE
calling .flatten / .flatten(level) on a hash

### ISSUE THREAD

**Issue by ghost** [makersacademy/problem-solving#113]
I've just been looking at the hash methods and i'm not sure i understand what the difference between calling .flatten on any given hash and .flatten(level) on the same hash is. When i've run both in my terminal I seem to get the same result:
2.4.0 :011 > capitals.flatten
 => ["Great Britain", "London", "France", "Paris", "Germany", "Berlin"] 
2.4.0 :012 > capitals.flatten(2)
 => ["Great Britain", "London", "France", "Paris", "Germany", "Berlin"] 

I'm not sure if i'm doing something wrong but would be grateful for any clarification!

**Comment by Pablo123GitHub** [comment]
Each item in your initial hash is a One-dimensional element: there is no array inside your hash. You only have strings. 

The number that you use with the flatten method makes sense only if you have an array in your hash.  The [documentation](https://ruby-doc.org/core-1.9.3/Array.html#method-i-flatten) says : 

> the optional level argument determines the level of recursion to flatten

...and this applies to arrays who may contain other arrays. 

**Example :** 

hashContaining1Array = {"Great Britain" => "London", "France" => "Paris", "Germany" => "Berlin", "NUMBERS" => [1, 2, 3, [4, 5]]}

`hashContaining1Array.flatten`

_the output is 
=> ["Great Britain", "London", "France", "Paris", "Germany", "Berlin", "NUMBERS", [1, 2, 3, [4, 5]]]_
 Note that "NUMBERS" is now a string element in the resulting array and the array [1, 2, 3, [4, 5]] is also part of this array. We get exactly the same result with hashContaining1Array.flatten(1)

But now if we run `hashContaining1Array.flatten(2)` we get the following result :  

_=> ["Great Britain", "London", "France", "Paris", "Germany", "Berlin", 
 "NUMBERS", 1, 2, 3, [4, 5]]_   

And with  hashContaining1Array.flatten(3), it will  "flatten" the same array one level further. 

`hashContaining1Array.flatten(3)`

_=> ["Great Britain", "London", "France", "Paris", "Germany", "Berlin",
 "NUMBERS", 1, 2, 3, 4, 5]_
