### ISSUE TITLE
Modifying your ~/.ssh/config file for macOS Sierra 10.12.2 or later

### ISSUE THREAD

**Issue by alexiscarlier** [makersacademy/problem-solving#114]
I haven't been able to modify my ~/.ssh/config file in the way suggested here https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent

This didn't stop me from adding a file to Github, but I feel like it could give me problems later. Has anyone been able to successully modify?

**Comment by alexscotttonge** [comment]
Are you able to explain what happened when you tried to do it?

**Comment by alexiscarlier** [comment]
I couldn't work out where/how to do it, so I didn't really attempt doing anything. I'm having trouble pushing to Github today, and my best guess is because of this.

**Comment by alexiscarlier** [comment]
Not being set up seems to mean that I have to reset my remotes every time- does that make sense to anyone?

**Comment by andyrow123** [comment]
You would need to edit or create the file and then enter the information and reload your Terminal
Use an editor like **nano** or **vi** to do this.
