### ISSUE TITLE
Using Ruby Index

### ISSUE THREAD

**Issue by will-gant** [makersacademy/problem-solving#12]
I sense as I write this that this is going to turn out to have a cringingly simple explanation, but I've spent a good 20 minutes googling and reading various guides, and am at a loss to get this working...

In exercise 15 of Learn Ruby the Hard Way, you're asked at one point to do the following: "Right now, run ri "File#open" and read the instructions."

I realise that ri is a command line tool for accessing ruby documentation, but no matter how I enter this command, I get 'Nothing known about File' (I get the same for various other things, like Array, which other online guides show should definitely be there).

![screenshot 2017-03-20 at 18 36 02](https://cloud.githubusercontent.com/assets/20523607/24113156/205135ee-0d9c-11e7-959a-28363cda537b.png)

I know I can access this same document online without any hassle, and that's what I'm going to do now, but it's just bugging me that I can't figure out how to do it the way the book is asking me.

I'm using ide.c9.io for all of the pre-course.

Thanks!

**Comment by TimRobinson1** [comment]
Have you tried typing "rvm docs generate" into the command line?  It should download the relevant documentation for a few minutes that it needs to refer you to.

Weirdly though, for me 'ri File#open' doesn't work, but ri File::open does.

**Comment by FiddlersCode** [comment]
I have the same problem.

**Comment by will-gant** [comment]
That worked - perfect. Thank you!

**Comment by will-gant** [comment]
All sorted for you Paula? (won't close this if you're still having trouble)

**Comment by itsalwaysbenny** [comment]
Could you leave this open for a few minutes, I'm on exercise 12 so might need this soon, using ide.c9.io as well.
 Thanks.

**Comment by will-gant** [comment]
Sure thing

**Comment by itsalwaysbenny** [comment]
Thanks for the help. Got the same problem

**Comment by FiddlersCode** [comment]
all good, thx!
