### ISSUE TITLE
~/.ssh/config - No such file or directory

### ISSUE THREAD

**Issue by SecretSurfSpot** [makersacademy/problem-solving#122]
Hi All,

I'm working my way through the: 
"Generating a new SSH key and adding it to the ssh-agent" 
Page - url below:
"https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/"

On the section "Adding your SSH key to the ssh-agent" I'm hitting an issue:

At Step 2, I enter the command "~/.ssh/config", but get the output "No such file or directory"

Everything up to this point seems to be fine:
 - I generated an ssh key.
 - eval "$(ssh-agent -s)" returned: "Agent pid 1834"

I'm on macOS High Sierra 10.13.6

Any help would be greatly appreciated :)

Thanks,
Andrew

**Comment by Lucx14** [comment]
looks like ~/.ssh/config is the path to a config file in the .ssh directory,
cd into .ssh from the root directory and the config file should be there to check or modify
hope that helps

**Comment by SecretSurfSpot** [comment]
Thanks Lucx14 for the response.

I've looked in the ~/.ssh directory, but there is no "config" file in there.

I have however managed go progress and gotten to be able to push and pull to github, so I'm guessing that step wasn't absolutely necessary?

Thanks again.

Andrew

**Comment by jdm79** [comment]
Hi Andrew,

I've attached a screenshot of my ~/.ssh config file for reference, anyway. 


<img width="540" alt="screen shot 2018-07-12 at 09 24 45" src="https://user-images.githubusercontent.com/11488167/42621374-876686a2-85b5-11e8-8fb2-bce75a8a1709.png">

**Comment by SecretSurfSpot** [comment]
Thanks jdm79!
