### ISSUE TITLE
CI Mystery step 3

### ISSUE THREAD

**Issue by leekarho** [makersacademy/problem-solving#123]
Hi,

I'm struggling with what to do here and what the actual objective of this step is or what I'm looking for! 

So I've got the list of streets but I've no idea what file the line numbers (from possible_witnesses) refers to?

Thanks!

**Comment by LondonJim** [comment]
Does the street name correspond with a file?

**Comment by andrewwood2** [comment]
You don't have to do a lot. Just find the files with the street names. You use those files in step 4.

**Comment by leekarho** [comment]
Thanks for your replies. 

I'm probably making it more complicated than it is!
