### ISSUE TITLE
Installing ruby 2.2.3 on PC

### ISSUE THREAD

**Issue by leekarho** [makersacademy/problem-solving#125]
Hi,

I'm on a PC and trying to install ruby version 2.2.3 on AWS (to do the mastery quizzes). 

However, I get this message:

![image](https://user-images.githubusercontent.com/40250827/42755309-8d56d796-88ef-11e8-96aa-c5c1d12ae641.png)

Any ideas (or alternatives)?

Thanks!

Kar-ho

**Comment by LondonJim** [comment]
This thread may help if you run into problems and need the specific version asked for, looks like you may have to sudo it.  https://forums.aws.amazon.com/thread.jspa?threadID=277360

**Comment by LazySamir** [comment]
For anyone else that may come across this issue. I found a solution of stackoverflow that worked for me. I needed to add my user to the rvm group by running:

`rvm group add rvm "$USER"`

then fixing the permissions with:

`rvm fix-permissions`

After a quick restart, it all ran fine.
