### ISSUE TITLE
rspec failure issue

### ISSUE THREAD

**Issue by LazySamir** [makersacademy/problem-solving#127]
Hi, I've run into an issue where I feel my program meets the specification but running rspec yields failures. 

Here is the rspec output for one question:

![image](https://user-images.githubusercontent.com/40366778/42828220-24e55d94-89e0-11e8-8003-b9751e99617a.png)

I was confused as to why there were extra characters on each line after 'Diff:' but I think that's explained by: 
`(/#{expected_output}/m).to_stdout.`
plus a join earlier in the file. 

If they are explained by this, then my program output should be, as far as I can see, correct. Happy to upload my code if needed and the spec (it's from chapter 6, question 4).

Many thanks!

**Comment by EsamAl-Dabagh** [comment]
I think your issue may be with the specification's use of "an hall" vs your use of "a hall".

**Comment by LazySamir** [comment]
Incredible; I must have looked over that a dozen times. You are completely correct, and that fixed it. Do you think this grammatical error was done on purpose? Devious! 

Thank you so much.
