### ISSUE TITLE
Error running test

### ISSUE THREAD

**Issue by fredericolawson** [makersacademy/problem-solving#128]
when attempting to run `rspec` on ...mastery-quizzes/chapter3/quiz1, the following is returned:

```
An error occurred while loading ./spec/question_1_spec.rb.
Failure/Error: require "safe_ruby"

LoadError:
  cannot load such file -- safe_ruby
# ./spec/question_1_spec.rb:1:in `<top (required)>'
No examples found.
```

I have tried reinstalling homebrew & rvm, but no luck...

**Comment by LondonJim** [comment]
Did the gems install correctly when you were going through the intial setup instructions?

**Comment by fredericolawson** [comment]
@LondonJim I think so, but with the following message (which I also get when navigating to mastery-quizzes)
```
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /Users/flawson/projects/mastery-quizzes/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.
```

**Comment by jdm79** [comment]
"gem install safe_ruby" could fix this issue temporarily, but it's strange why it didn't install the first time

**Comment by fredericolawson** [comment]
Done, thank you :)
