### ISSUE TITLE
Rake command not working on c9.io when checking solutions for Ruby Kickstart 

### ISSUE THREAD

**Issue by BertZZ** [makersacademy/problem-solving#13]
When I try to check solutions using rake I get the following 

ubuntu@bertz-pre-course-4555637:~/workspace/projects/ruby-kickstart/session1/challenge$ rake 1:1
(in /home/ubuntu/workspace/projects/ruby-kickstart)
rake aborted!
Gem::LoadError: Could not find 'rspec' (~> 3.0) among 16 total gem(s)
Checked in 'GEM_PATH=/usr/local/rvm/gems/ruby-2.3.0:/usr/local/rvm/gems/ruby-2.3.0@global', execute `gem env` for more information
/home/ubuntu/workspace/projects/ruby-kickstart/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)

Anyone give me any suggestions to what I can do to fix this, this error message doesn't make much sense to me

**Comment by ffasolin** [comment]
Looks like you need to install rspec, maybe. Try running gem install rspec.

**Comment by BertZZ** [comment]
Thank you so much, that worked :)
