### ISSUE TITLE
Error and not an error using rspec 

### ISSUE THREAD

**Issue by LondonJim** [makersacademy/problem-solving#130]
Trying to figure out what this means.
First screen shot is after I run `rspec` from the quiz1 directory.  It actually runs the game and asks for my input, when the game ends it then automatically runs the checks and gives me the all clear with no errors, but should it be asking for my input? The second screen shot is when I run rspec `spec/question_1_spec.rb` from the same directory. My code has not changed but I get a NoMethodError. Can anyone enlighten me? (This is chapter 9 which only has one question). Thanks!

<img width="761" alt="screen shot 2018-07-18 at 20 44 24" src="https://user-images.githubusercontent.com/39761427/42904356-b4da6f1a-8acc-11e8-9c16-cd37a84ab60a.png">

<img width="764" alt="screen shot 2018-07-18 at 20 44 50" src="https://user-images.githubusercontent.com/39761427/42904374-c2442c68-8acc-11e8-9212-9ccd5ace0dc7.png">

**Comment by Lucx14** [comment]
i think that second error might come if you are calling the run_game method at the bottom of your program, if its in there just take it out and rspec should call it as part of its tests

**Comment by LondonJim** [comment]
Champion! That did the trick
