### ISSUE TITLE
Inadvertently modifying original array

### ISSUE THREAD

**Issue by fredericolawson** [makersacademy/problem-solving#132]
Hi, what I'm trying to do here is modify one section of the river each time (and then have it revert to its original on the next while loop). Therefore I've made a new array (new_river) inside the while loop which includes the modified river section. What I am hoping would happen is each lap of the while loop would reset the river object to it's original state, as I am reassigning `new_river` to `river` each time. However, instead, the original `river` array is being modified - how can I stop that happening? Thank you!

```
counter = 0

river = [
  '-----',
  '--C--',
  'CC-CC',
  'CC-CC'
]

while true do


  puts 'Type left, right or neither'
  move = gets.chomp
  if move == 'break'
    break
  end

  broken = river[counter].split("") # taking the relevant element of the river, and splitting it into letters

  broken.delete_at(2) # Deleting river character in arbitary position
  broken.insert(2,"P") # Replacing deleting river character with P
  # combining to make one joined up piece of river again
  joined = broken.join("")

  new_river = river # make a copy of the river
  new_river.delete_at(counter) # delete the river section at the counter position
  new_river.insert(counter,joined) # replace the river section with the new slice of river
  print new_river

  counter += 1
end
```

**Comment by LazySamir** [comment]
Sorry only have a minute before I shoot off; will look at this more when I get back. 

A quick solution to achieve what you're asking (although it does go against the DRY principle, a bit) would be to enter the array manually rather than assigning it to the original. So:
`new_river = [
  '-----',
  '--C--',
  'CC-CC',
  'CC-CC'
]`

**Comment by LondonJim** [comment]
From what I understand (I think this is right) when you made `new_river = river` you are making `new_river` have the same object id as `river`.  When you use `delete_at` and `insert` on `new_river` you are changing both of them since they hold the same object id in the memory.

**Comment by LondonJim** [comment]
`Array.new` can take parameters

**Comment by fredericolawson** [comment]
Thanks @LazySamir @LondonJim , in the end I wrote out the river as an array of arrays which made things simpler :)
