### ISSUE TITLE
Authentication failed when pushing the commit

### ISSUE THREAD

**Issue by AntonioDaria** [makersacademy/problem-solving#134]
I have encountered a technical issue while pushing the first commit on step 1
I think is to do with the way I have cloned the rep (with the HTTPS protocol)

now I get the following error message:
![image](https://user-images.githubusercontent.com/24396579/43833115-9f2343f0-9b01-11e8-9085-1c26dbde53fc.png)

**Comment by soph-g** [comment]
Hi Antonio, you are attempting to push using SSH, in order to do this you'll need to configure you SSH setup following these instructions: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by AntonioDaria** [comment]
Hi Sophie,
i did configure my SSH setup and it was all fine. i think the issue s that when i cloned the repo i cloned it using HTTP instead of SSH. could this be the reason ?

**Comment by soph-g** [comment]
That's very likely. Although usually it sets up the remote using the method that you used to clone the repo. You could try removing the repo locally and re-cloning it using SSH, if that's how you'd like to push up changes.

**Comment by soph-g** [comment]
Actually I was mistaken, the URL you are trying to push to is a HTTPS one, however it should still work. If you have 2FA set up on your account then that might be causing a problem, you'll need to create a Personal Access Token. This help documentation gives more information: https://help.github.com/articles/accessing-github-using-two-factor-authentication/

**Comment by soph-g** [comment]
Is this issue now resolved?
