### ISSUE TITLE
Having trouble adding SSH keys to ssh-agent

### ISSUE THREAD

**Issue by djstephenson7** [makersacademy/problem-solving#137]
My laptop software version is OS High Sierra 10.13.6, so I need to 'modify my ~/.ssh/config file to automatically load keys into the ssh-agent and store passphrases in my keychain.'
I get these messages when I try this, however.

![screen shot 2018-08-09 at 10 55 39](https://user-images.githubusercontent.com/41509062/43892248-55e70146-9bc3-11e8-9e65-4e749684ed13.png)

**Comment by soph-g** [comment]
Hi Daniel,

I presume you are attempting to follow these steps: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

They are specifying that you need to open the `~/.ssh/config` file, and add in this text:
```
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_rsa
```

The text is not a command to run in Terminal.

you should be able to open the file you need to edit in Atom using the command `atom ~/.ssh/config` presuming you are using Atom as your text editor.

**Comment by djstephenson7** [comment]
Done. Thanks
