### ISSUE TITLE
Stuck on 

### ISSUE THREAD

**Issue by FlorenceHapgood** [makersacademy/problem-solving#138]
Hi, I'm having a lot of trouble with pushing my local repo to Git (lesson 43) when I do "git push -u origin master" I get this...

"Florences-MBP:gitDir florencehapgood$ git push -u origin master
Username for 'https://github.com': FlorenceHapgood
Password for 'https://FlorenceHapgood@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/FlorenceHapgood/playing-with-git.git/'

I've tried re-entering my password many times. I've created a SSH key and added it to my GitHub account. I'm guessing it's either...

a) a problem with this bit "If you're using macOS Sierra 10.12.2 or later, you will need to modify your ~/.ssh/config file to automatically load keys into the ssh-agent and store passphrases in your keychain." 
I thought that I'd  created the "~/.ssh/config" with vm and added in the Host* etc... but maybe I've done that wrong. I tried to do it with atom but I was a bit unclear about the instructions....I might need very clear step by step instructions on this one!

b) it could be a problem with the fact that I change my github account today. For various reasons I deleted my old account and opened a new one. But I tried all this with my new account so I don't know why it wouldn't work. 

Thanks!

**Comment by FlorenceHapgood** [comment]
er sorry part of my comment is crossed out...(?)I hope you can view it and it makes sense.

**Comment by emmaalbury** [comment]
I briefly had this issue but fixed it. This is a really obvious suggestion, but I think we all overlook the obvious sometimes: If you haven't already, I suggest you log out of GitHub and try to sign in again. I was accidentally using an old password in the command line and just needed to use one I had recently reset to sign in to GitHub. If the username and password works to sign in at least you can eliminate that as an issue. Good luck!

**Comment by FlorenceHapgood** [comment]
So....it turns out you are right and that was the issue (or one of). What. An. Absolute. Nincompoop. I was at that for a loooooong time. Thank you so much Emma!!! I'd entered my github password wrong in the first place!! Oh Lord how embarrassing. 
I wish I could help you with you question btw but I don't think I'm there yet.

**Comment by emmaalbury** [comment]
AWESOME!!!! Don't be embarrassed. I've had pleeeeeeeeenty of "duh Emma!" moments already in this course (and even one in my interview!). I'm sure I'll have many more too. I think we're all bound to at some point. It's just part of the journey we're on. Keep on keeping on! : )

**Comment by FlorenceHapgood** [comment]
Ah thank you Emma, that's so sweet!! Right back at ya!
