### ISSUE TITLE
I'm with Stupid

### ISSUE THREAD

**Issue by alakijaayo** [makersacademy/problem-solving#139]
Okay this one is completely on me, but wanted to know if I have to go back and redo this, or if there is a work around.

So I got to Lesson 45 and the part where it asks you to click on moreGitText. However, back when we were deleting gitText in lesson 40, I (stupidly) also deleted moreGitText thinking that there was no need for it. 

After realising we did need it, i tried adding it back into the program, but now when i go to pull the code, I get:

You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

Do i need to go back through the lessons and redo the whole git process? or is there a way to work around this??

**Comment by ShinyVerse** [comment]
Hello. You shouldn't need to redo. 

Just a few questions:
If you type git branch into the Terminal what do you have returned to you?
Do you now have your new moreGitTest listed when you command ls?
What do you have when you command pwd?

**Comment by alakijaayo** [comment]
Thanks for your response. 

When I type in git branch to the terminal, I get:

* (HEAD detached from f91645a)
  master

and when I type in ls I do get moreGitText back:

Elaines-MBP:gitDir Elaine$ ls
moreGitText

**Comment by alakijaayo** [comment]
So just put git pull in again and it is still giving me this:

You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

Is it just best for me to start again?

**Comment by ShinyVerse** [comment]
If you do 
`git checkout master`
what does it give you?

**Comment by alakijaayo** [comment]
Thanks. just tried what you asked. This was the response:

Elaines-MBP:gitDir Elaine$ git checkout master
A	moreGitText
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

Also, saw what you had asked (with regards to trying to copy my mistake), I would gladly give details if needed (was a pretty stupid one on my part lol).

Lastly, if this is up to date, will it show on the GitHub part of the lesson? Know most of this has to be done on Github.

Thanks ever so much for your help.
