### ISSUE TITLE
Chapter Nine Question One Test Keeps Failing

### ISSUE THREAD

**Issue by Kharouk** [makersacademy/problem-solving#141]
So for the last couple of hours, I've been trying to solve chapter nine's challenge. I even solved it on my own computer, but when I use RSpec to check if it's right, it gives me many errors. 

The code: 
```ruby
def random_card
  cards = ["two", "three", "four", "five", "six", "seven",
           "eight", "nine", "ten",
           "jack", "queen", "king", "ace"]

  cards[rand(13)]
end

def move
  while true do
    puts "Make a move"
    move = gets.chomp
    if move == "hit"
      return "hit"
    elsif move == "stick"
      return "stick"
    end
  end
end

def score(array_of_cards)
  array_of_cards.reduce(:+)
end

def run_game
  cards_in_hand = []
  hand_sum = []
  hand_score = {
    "two" => 2, "three" => 3, "four" => 4, "five" => 5,
    "six" => 6, "seven" => 7, "eight" => 8, "nine" => 9,
    "ten" => 10, "jack" => 10, "queen" => 10, "king" => 10,
    "ace" => 11
  }

  while true do
    if move == "hit"
      card = random_card
      cards_in_hand.push(card)
      puts cards_in_hand
      hand_sum.push(hand_score[card])
      puts "Score so far: #{score(hand_sum)}"
    else
      if score(hand_sum) <= 21
        puts "You scored: #{score(hand_sum)}"
        break
      else score(hand_sum) > 21
        puts "You busted with: #{score(hand_sum)} "
        break
      end
    end
  end
end
```
This works on my local computer as expected. When I 'hit', I get the name of a random card as well as the points associated with it. It adds up as I continue typing 'hit. When I type 'stick', the terminal returns the final sum of all the cards and exits the game. Exactly what I thought the assignment wanted. 

However, when running through RSpec, I get errors such as this:
```shell
  2) Q1. Blackjack #hand_score individual cards scores `"two"` as 2
     Failure/Error: expect(score(["two"])).to eq(2)

       expected: 2
            got: "two"

       (compared using ==)
     # ./spec/question_1_spec.rb:80:in `block (4 levels) in <top (required)>'
```
Or: 

```shell
  16) Q1. Blackjack #run_game `puts`ing outcome of game player takes too many cards and busts `puts`es You busted with: 28
      Failure/Error:
        expect { run_game }
          .to output(/#{expected_output}/m).to_stdout

        expected block to output /You busted with: 28
        /m to stdout, but output "Make a move\nseven\nScore so far: 7\nMake a move\nseven\nking\nScore so far: 17\nMake a move\nseven\nking\nace\nScore so far: 28\nMake a move\nYou busted with: 28 \n"
        Diff:
        @@ -1,3 +1,15 @@
```
For the first error my guess is that the RSpec test is looking for a specific way I'm naming my numbers? However I've tried switching the orders but it's not really working. 

The second error seems to be giving me a new problem that wasn't included in the question? Do I needed to include another conditional regarding 'too many cards' that's above 28?

I'll keep trying to fix it but hopefully someone could shed some light on where I'm going wrong.

**Comment by Kharouk** [comment]
Alright, I'm excited because I found my silly mistake. Like most of the problems I face, I just had to read the test errors... Spoilers ahead!! 
I had to pay attention to this specific error. 
```shell
 2) Q1. Blackjack #hand_score individual cards scores `"two"` as 2
     Failure/Error: expect(score(["two"])).to eq(2)

       expected: 2
            got: "two"

       (compared using ==)
```
Right where it says: expect(score(["two])). I totally undermined my score method. I simply wrote a one-liner code that adds everything up, assuming (never assume) that would just add numbers. But the test was checking the method its own way; by inputting a card's string and seeing if it returns an integer! 

So I originally wrote: 
```ruby
def score(array_of_cards)
  array_of_cards.reduce(:+)
end
```
But it had to be more sophisticated to pass the test. So I changed it to:
```ruby
def score(array_of_cards)
  hand_score = {
    "two" => 2, "three" => 3, "four" => 4, "five" => 5,
    "six" => 6, "seven" => 7, "eight" => 8, "nine" => 9,
    "ten" => 10, "jack" => 10, "queen" => 10,
    "king" => 10, "ace" => 11
  }
  sum_of_cards = []
  array_of_cards.each do |card|
    hand_score.each do |key, value|
      if card == key
        sum_of_cards.push(value)
      end
    end
  end
  sum_of_cards.reduce(:+)
end
```
And it worked! No 'naming my numbers' or 'including another conditional.'  Just not paying closer attention to the error I was given. 

Sorry for bothering anyone with this! Hopefully, my mistake could help someone else.

**Comment by olliebaum** [comment]
So ouf of curiosity, where is this problem from? Chapter 9 of what resource?

**Comment by camjw** [comment]
It's from the week 2 stuff, there are a load of quizzes to do
