### ISSUE TITLE
Start the Ruby with mastery learning curriculum. (link doesn't work)

### ISSUE THREAD

**Issue by AntonioDaria** [makersacademy/problem-solving#142]
Hi, Has anybody experienced a problem opening the link to the learning curriculum on week 2?
I cannot access the page , I get the following message: 

makersacademy.gitbooks.io’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by Kharouk** [comment]
Hey I just checked Gitbook's website and it looks like it's down as well. Maybe they're having server issues or are down for maintenance. 

http://gitbooks.io/

**Comment by AntonioDaria** [comment]
Hi, Ok, will need to try again later i guess. thx!!

**Comment by Kharouk** [comment]
Hey is it working for you now? I just checked and it looks to be back online.

**Comment by AntonioDaria** [comment]
Yes working now!!
