### ISSUE TITLE
Chapter 4, Question 1

### ISSUE THREAD

**Issue by djstephenson7** [makersacademy/problem-solving#144]
Hi guys,

I'm attempting the part of the question where I have to replace every number divisible by 3 with "Fizz".

As you can see from the screenshot, it puts "Fizz" after the relevant number, but it doesn't replace it. 

Any ideas on how to replace the number with the string?

![screen shot 2018-08-14 at 13 43 14](https://user-images.githubusercontent.com/41509062/44092349-20ad0ee0-9fc8-11e8-8e05-5de040862aef.png)

**Comment by NadiaAiraf** [comment]
Hey Daniel, you need to add an "else" to your if statement and move the "puts number" into that section. 

This way when the number is divisble but 3 it will put fizz and for any other scenario it will put the current number.

**Comment by djstephenson7** [comment]
Hi Nadia,

Worked like a dream, thanks!

**Comment by djstephenson7** [comment]
Woops, meant Aidan
