### ISSUE TITLE
Mastery quizzes Chapter 4 - Question 3

### ISSUE THREAD

**Issue by darciew** [makersacademy/problem-solving#145]
Fibonacci numbers has me very confused!

Been trying all day to get to the bottom of this but just can't work out how to add the previous two Fibonacci numbers together.

This is my latest (bad attempt) but it just creates an infinite loop..
<img width="327" alt="screen shot 2018-08-14 at 17 43 05" src="https://user-images.githubusercontent.com/31215123/44105409-8c88c4b2-9fe9-11e8-924b-fb506a443ef6.png">

Has anyone had any success on this one?

**Comment by m-rcd** [comment]
Hey Darcie, 
Try to make this simpler on yourself by maybe starting with creating an array with the numbers that the challenge is giving you. Like: `array = [0, 1]`. start off by just trying to add these two together and then pushing the result into that array. From there you can work on a loop to keep going. 
Hope this is helpful, let me know if not!

**Comment by darciew** [comment]
Hey Marianne

Thanks for the reply :)

Sounds like a good idea to me, what do you mean by pushing the result into the array?

**Comment by m-rcd** [comment]
I meant like literally the `array.push` method but you can use whichever appending method you like!

**Comment by darciew** [comment]
ahh I see ok I'll give that a try and see what happens, thanks!
