### ISSUE TITLE
Chapter 6, question 1

### ISSUE THREAD

**Issue by djstephenson7** [makersacademy/problem-solving#147]
Hi guys, 

I'm trying to solve question 1 by writing a loop that stores the user's input to an array and returns the sum when the user enters "stop".

Problem is, it stores "stop" to the array. Any ideas?

![screen shot 2018-08-16 at 12 08 25](https://user-images.githubusercontent.com/41509062/44205617-de115900-a14e-11e8-979f-d19027e6f656.png)

**Comment by ShinyVerse** [comment]
Hello,

Try to think about what you're applying the conditional statement to.

On the line below your first input request you are pushing input without testing.

If I convert your code into English it reads as follows: 

Give me a number
Input : "10"  (gets returns a string to the variable input, remember this for your conditional too.) 
Save input into my array.

if "10" == Integer 
ask 
get input
add input.

..

I hope this helps.

**Comment by afaraone** [comment]
Also, you're using gets twice. Everytime you use "gets" it will prompt the user for input. The gets in line 39 won't get tested as it is inside the if condition.

**Comment by ShinyVerse** [comment]
Try to make that while work for you more. You only need to break out when the user requests to stop.

**Comment by afaraone** [comment]
One more thing, everything inside a loop or a conditional should be indented.

```
while conditional [do]
  code
end

if conditional
  code...
elsif conditional
  code...
else
  code...
end
```

**Comment by afaraone** [comment]
(I can't seem to get indentations to work on here lol)

**Comment by ShinyVerse** [comment]
You can write code here (and on slack) by putting ``` before and after your code, making sure those are on their own line if multiline code. 

```
while
  code
end
```
Type spaces in place of tab to indent. Someone else might be able to say how to indent another way, but I don't know.

**Comment by afaraone** [comment]
Yep, I'm using vim with an option to automatically convert tabs to whitespace :)
https://vi.stackexchange.com/questions/4141/how-to-indent-as-spaces-instead-of-tab
(read the last comment)

**Comment by djstephenson7** [comment]
Thanks guys!
