### ISSUE TITLE
Chapter 6 Question 3

### ISSUE THREAD

**Issue by alakijaayo** [makersacademy/problem-solving#148]
Having a problem with getting either Atom or the gems to accept this answer and I am not sure what the problem is. From a base standpoint the program does give me the answers I want but this does not get accepted when I try to run through spec. However, if I try to add breaks into the code, I get an error message saying that the break is invalid. 

Not sure what I have to do, or do i need to start from scratch?
![screen shot 2018-08-16 at 13 46 35](https://user-images.githubusercontent.com/41967698/44209559-cab8ba80-a15b-11e8-8305-ae1e87b0bbd2.png)

**Comment by djstephenson7** [comment]
It could be down to inconsistent indentation

**Comment by camjw** [comment]
I think the issue is that you haven't included a while loop. The program is supposed to continue running until the player walks into the sunlight (so they can go from the passage to the cave as many times as they want) and the breaks are to break the while loop. Hope this helps!

**Comment by alakijaayo** [comment]
@camjw cheers for that. Working on it now. Much appreciated
