### ISSUE TITLE
Grep Week 1 challenge

### ISSUE THREAD

**Issue by T-Miller0** [makersacademy/problem-solving#149]
Hey Guys, I am a little behind due to work. I cannot seem to get the grep command to work. Are there any suggestions? 

![screenshot 3](https://user-images.githubusercontent.com/42030623/44211973-0787b000-a162-11e8-9033-6091c9c0856c.png)

**Comment by camjw** [comment]
Hey there, I think you need to search for CLUE instead of clue because grep is case sensitive, then it should work
