### ISSUE TITLE
LRTHW ex 16 - can't read the file

### ISSUE THREAD

**Issue by FiddlersCode** [makersacademy/problem-solving#15]
![image](https://cloud.githubusercontent.com/assets/7489685/24141794/80c7f2fc-0e1c-11e7-8518-b42e9605ed60.png)

As you can see, reading the file isn't working!!

```
# sets a variable filename to equal the argument
filename = ARGV.first

# puts string
puts "We're going to erase #{filename}"
# CTRL-C interrupts the program
puts "If you don't want that, hit CTRL-C (^C)."
# could be any key - not just return
puts "If you do want that, hit RETURN."

# accepts user input of any key
$stdin.gets

puts "Opening the file..."
# sets a variable called target which will open the filename and erase the contents of the file.
# use a as a second argument if you want to append
target = open(filename, 'w')

puts "Truncating the file.  Goodbye!"

puts "Now I'm going to ask you for three lines."

print "line 1: "
line1 = $stdin.gets.chomp
print "line 2: "
line2 = $stdin.gets.chomp
print "line 3: "
line3 = $stdin.gets.chomp

puts "I'm going to write these to the file."

target.write(line1 + "\n" + line2  + "\n" + line3 + "\n")

puts "And now, let's read the file!"

open(target)

print target

puts "And finally, we close it."
target.close
```

**Comment by nikeshashar** [comment]
It's easier to read your code now. 

Anyone hazard to take a guess what's going wrong here?

**Comment by Robert-G-J** [comment]
Hey @pmuldoon86 You're missing a `target.truncate(0)` under the puts statement. That just means you won't have deleted the file's contents, thought.

Also, target is a 'file object' rather than a string, so you have to call .read on it i.e. `print target.read` EDIT: You're likely to need to open the file first, too. I expect you'll need the same as `target = open(filename)`. Then close it.

I think... 🙏 

i.e. 
```Ruby
puts "Let's read the file we just wrote: "
target = open(filename)
print target.read
target.close`
```

**Comment by enonnai** [comment]
Rob, I tried commenting out that line - `target.truncate(0)` - and it still works, thanks to line 10 (please refer to lines in the original code), as Nikesh commented:
 "sets a variable called target which will open the filename and erase the contents of the file.
 use a as a second argument if you want to append"
`target = open(filename, 'w')`

**Comment by anthony-crisp** [comment]
Ye, I think you need to pass a block to open(target) to get it to read otherwise you are just creating something new, maybe? I need to read up on this more.

**Comment by j311y** [comment]
Hey @pmuldoon86 here's one solution:

```
filename = ARGV.first

puts "We're going to read #{filename}"
puts "If you don't want that, hit CTRL-C (^C)."
puts "If you do want that, hit RETURN."

$stdin.gets

puts "Opening the file..."
target = open(filename)

puts target.read # Here is where the file gets printed on command line

puts "File closed."
target.close
```

**Comment by enonnai** [comment]
I got around it by closing the file and reopening it again in the same script, assigning a new variable. Still working on how to avoid this extra step.

**Comment by enonnai** [comment]
I found a solution for reading the file without having to close it and re-assign variables. Re-reading the Drills helped me out :)

**Comment by anaalta** [comment]
@enonnai without closing first? I thought that's like "save"... pretty curious to see your solution :).

**Comment by FiddlersCode** [comment]
Thanks all, sorted!  I think I wasn't quite understanding the drill's purpose and now I got it, which helps.  :) . And the 'w' flag rewrites the contents of the file so the truncate method is redundant.  Yay refactoring.
