### ISSUE TITLE
Installing Ruby 2.2.3 on AWS cloud 9

### ISSUE THREAD

**Issue by T-Miller0** [makersacademy/problem-solving#151]
I have tried a number of different things that were suggested but I keep getting the same error.
Does anyone have any suggestions?

![screenshot 6](https://user-images.githubusercontent.com/42030623/44267618-e341d700-a226-11e8-8341-cae3ff3b3d06.png)

**Comment by NadiaAiraf** [comment]
Hey I had this same problem and the fix on this link worked out for me

https://community.c9.io/t/cant-download-ruby-version-2-3-0-on-cloud-9-ide/24338

**Comment by T-Miller0** [comment]
Iv managed to get ruby installed, but now when i come to perform cd path/to/root/of/this/repo. It says, "No such file or directory". Have I missed something?

**Comment by T-Miller0** [comment]
Thank you 👍
