### ISSUE TITLE
Chapter6 question 4

### ISSUE THREAD

**Issue by AntonioDaria** [makersacademy/problem-solving#152]
Hi, I have got a problem when try to pass the tests on the 4th questions, My program works as intended but fails some of the test, i have tried to get to the bottom of it by pair programming too but could not find the solution, se my code below:
```
location = "hall"
answer = ""
while answer != "quit" do
  answer = gets.chomp
  if answer == "quit"
    puts "Bye!"
    break
  end
  if (answer == "look" && location == "hall")
    location = "hall"
    puts "You are standing in a hall with a marble floor. You see a door."
  elsif (answer == "north" && location == "hall")
    location = "study"
  elsif (answer == "south" && location == "study")
    location = "hall"
  elsif (answer == "look" && location == "study")
    location = "study"
    puts "You are in a warm and cosy study. You see a safe. You see a desk."
  elsif (answer == "look at desk" && location == "study")
    puts "You see a piece of paper that reads,The combination is 2451."
  elsif (answer == "enter combination 2451" && location == "study")
    puts " You see some diamonds in the safe, pick them up and make your escape"
    break
  end
end
```

**Comment by AntonioDaria** [comment]
![image](https://user-images.githubusercontent.com/24396579/44271986-7bde5400-a233-11e8-9217-1d0563fb4fd3.png)

**Comment by ShinyVerse** [comment]
Hey, I've been pairing with Antonio and I'm having trouble helping with this error message, because for me it looks like it is returning what it is expecting.

If anyone can shed some light on what's going on with this error it would be interesting to know.

**Comment by m-rcd** [comment]
it s supposed to be : "You are standing in **an** hall with a marble floor. You see a door."
hope that helps

**Comment by ShinyVerse** [comment]
Oh wow. We were blind to this. Thank you!
