### ISSUE TITLE
Chapter 3

### ISSUE THREAD

**Issue by T-Miller0** [makersacademy/problem-solving#153]
Hey guys, I am not sure what I have done wrong. 
Any ideas?
![screenshot 9](https://user-images.githubusercontent.com/42030623/44301055-ca115700-a308-11e8-995c-d55cc58d64a7.png)

**Comment by emmaalbury** [comment]
Hey there. The last two variables are incorrect (four and zero). Without wanting to give too much away, I suggest you check out Ruby documentation to see how modulo works. You can see an explanation here https://www.ruby-forum.com/topic/181880. Hit me up again if you're still struggling with it : )

**Comment by cristinaocanamanzano** [comment]
Hello! Yes, exactly, I think Emma's right. However, the screenshot you attached shows 7 failures - I am not sure why it says the other operations are also wrong. Maybe try again after fixing the last two operations?

**Comment by T-Miller0** [comment]
Hey, I thought I had the modulo's wrong. It is still returning that I have got them all wrong.

**Comment by emmaalbury** [comment]
What do your rspec errors say? They'll usually tell you exactly what the issue is. Often for me it's just indentation/spacing issues I have to fix up.

**Comment by T-Miller0** [comment]
![screenshot 11](https://user-images.githubusercontent.com/42030623/44301500-d816a600-a30f-11e8-9452-4aa19ea254ea.png)

**Comment by cristinaocanamanzano** [comment]
Could you also try fixing the last operation and re run the check?

**Comment by emmaalbury** [comment]
If you scroll up you should be able to see a breakdown of each error.

**Comment by cristinaocanamanzano** [comment]
Could it be that you have not saved the changes to the file and the check is being performed on the initial file without the solutions?

**Comment by T-Miller0** [comment]
That worked! Always something so trivial. Thanks a lot for your help guys

**Comment by cristinaocanamanzano** [comment]
Yay, glad it worked :)
