### ISSUE TITLE
Chapter 7, question 2 error message

### ISSUE THREAD

**Issue by emmaalbury** [makersacademy/problem-solving#154]
Although it's running fine elsewhere, rspec is showing two errors for my chapter 7 question 2 program. It seems to be the same issue in both errors. However I don't really understand the error as I seem to be getting the correct group outputs. Is it something to do with the prompts I'm puts'ing? Thanks.

![screen shot 2018-08-19 at 4 21 33 pm](https://user-images.githubusercontent.com/25674795/44310428-0955ab80-a3ce-11e8-8497-557b52ec68e9.png)
![screen shot 2018-08-19 at 4 22 04 pm](https://user-images.githubusercontent.com/25674795/44310459-85e88a00-a3ce-11e8-9d8f-9e655b9d084c.png)

**Comment by darciew** [comment]
Hey Emma,

Is it because when you enter the number of a group to print out they are puts'ed onto separate lines, instead of being on the same line just separated by a comma and a space?

**Comment by emmaalbury** [comment]
That was a problem. Yes. But by fixing that I opened a whole new can of worms (or errors?). I've re-written a heap of my code and now it's passing. Thank you!
