### ISSUE TITLE
undefined method

### ISSUE THREAD

**Issue by T-Miller0** [makersacademy/problem-solving#155]
Hey guys, I keep getting undefined method "number". Any ideas on what to do?

![screenshot 12](https://user-images.githubusercontent.com/42030623/44333263-3eadd800-a466-11e8-9b08-2bc7b49e0a62.png)

**Comment by jonurry** [comment]
I think that you need to look at where you are placing the brackets on line 21. At the moment, ruby is interpreting 'number' as a method rather than a variable.

**Comment by m-rcd** [comment]
(number % 3 == 0) && (number % 5 == 0)  try doing that , should work. Let me know if still not working :)

**Comment by T-Miller0** [comment]
Hey Marianne, that still returns the error. I have removed the brackets and the error now has gone. There must be something missing in my code because it isn't puting FizzBuzz, so will have to play around with it.

**Comment by jonurry** [comment]
Think about the order in which you are doing the modulo (%) comparisons. If (number % 3 == 0) is true then you may never get to the 'FizzBuzz' comparison on line 21.

**Comment by T-Miller0** [comment]
Thanks Jon, Iv managed to sort the code out. I am just getting some errors off of format now
