### ISSUE TITLE
Chapter 7, question 1

### ISSUE THREAD

**Issue by djstephenson7** [makersacademy/problem-solving#156]
Hi guys,

I've approached question 1 by getting the input, removing the commas and iterating over each number. The last step is to convert the input into a 'bar chart' format, but I've no idea how I would do this, even in theory. Can someone share some insights?

Thanks

![screen shot 2018-08-20 at 12 49 25](https://user-images.githubusercontent.com/41509062/44338945-8b4ddf00-a477-11e8-86d1-9c92878ff33c.png)

**Comment by alakijaayo** [comment]
Hey! You might want to look at the input and see if that is causing the issue. From what I see, your split will already make an array, so by the looks of it your putting an array into an array.

Also, you need to change your string output into an integer.

**Comment by afaraone** [comment]
Something to help you work it out. Any input received with `gets` is a string. You need integers in order to work out this exercise.

**Comment by FlorenceHapgood** [comment]
Yeah chapter 7 is tough, only just finished it - so the way I thought about it was...
For each unit/"1" WITHIN a number you need to print "-". So, if you have 4, you need to print "-" four times, so maybe think about how you can iterate 4 times for example and print "-" each time, and then you can work on how make that flexible for whatever number is inputted. And afaraone is right, you do need to make your gets integers....
