### ISSUE TITLE
Chapter 6 question 3

### ISSUE THREAD

**Issue by T-Miller0** [makersacademy/problem-solving#157]
Hey guys, I can't seem to get the second loop to go to the next stage (the second north).

Any suggestions?

![screenshot 13](https://user-images.githubusercontent.com/42030623/44354922-0bd60500-a4a3-11e8-83a2-c325da3a2a91.png)

**Comment by AntonioDaria** [comment]
Hello,
you will need to set a variable that will allow you to keep track of your player ( i assume you called that step)
step needs to change its value everytime a condition is evaluated and met.

**Comment by T-Miller0** [comment]
I thought that the step += 1 would change it's value?

**Comment by AntonioDaria** [comment]
i think step needs to change (set ) value as soon the condition "north" it is met and then back again when the player goes back at the next if "south"
let me know if it is clear

**Comment by T-Miller0** [comment]
I think I follow, I have moved "steps += 1" within my "if user == south" statement and Im still getting the same error.

**Comment by AntonioDaria** [comment]
have you tried by setting it manually to its new value ?

**Comment by T-Miller0** [comment]
as in "steps = steps + 1"?

**Comment by AntonioDaria** [comment]
as in step = 1 or step = 2  if you are in the cave 
So you start with:
```
 step = 1
then if user == "north"
step = 2
puts " YOU ARE IN A CAVE "
```

**Comment by AntonioDaria** [comment]
See if you can follow from there, i don't want to give too much away

**Comment by T-Miller0** [comment]
I can't seem to get from the first north (line 31) to the next stage (line 49). Are there any suggestions?

![screenshot 14](https://user-images.githubusercontent.com/42030623/44403426-5069ab00-a54c-11e8-88d1-2b96b5f48b13.png)

**Comment by jonurry** [comment]
The first thing I would suggest is to tidy up the indentation of your code.
Once the code blocks line up it will be a lot easier to follow the flow of the code.

**Comment by ShinyVerse** [comment]
I think you have overcomplicated and the flow is causing you a hard time. Try to get one while loop to work hard for it's place in your code. 

Just an approach to the logic, using your step variable to track the players location:

You have three steps to your game. 
Step 1 they are in a passage
Step 2 they are in a cave 
Step 3 they are outside and the game should end.

If they go north it's a step forward, if they **can** go south it's a step backwards.

Based on their step you can tell the player where they are located. While they have not reached step 3, they continue to play.

The instructions only give the player the option to go north in the passage, anything else and nothing happens.

**Comment by T-Miller0** [comment]
I was massively over complicating it. Thanks guys for your help!
