### ISSUE TITLE
Ch8. q2. 

### ISSUE THREAD

**Issue by FlorenceHapgood** [makersacademy/problem-solving#159]
Hi guys, 

Does anyone know if we're allowed to only use the "people" array that they've given us as data, and otherwise comment it out and create new hashes and arrays? The spec does accept that, but I have a feeling that this is not what's intended and that we might be supposed to manipulate the people array as it is, just as he does at the end of chapter 8. I wouldn't want to be cutting too many corners at this stage, and of course mainly I don't want to cheat myself out of all the despair and angst that will accompany that task :)

**Comment by FlorenceHapgood** [comment]
(I meant chapter 8, not 7, just changed the title!)

**Comment by jonurry** [comment]
Hi Florence,
I left the people array and hashes intact and was able to iterate over them to extract the names of the people based on the category and value inputted.
Hope that helps...

**Comment by ShinyVerse** [comment]
Hey Florence, 

I think any code present is set the way it is to guide you towards specific challenges based on how it has been written. 

Learning to navigate through hashes are important as you'll later, most likely, have to make use of JSON.

**Comment by FlorenceHapgood** [comment]
Ah thanks guys, ok I think you're right and I should do it the proper way, thanks for your help!
