### ISSUE TITLE
Kata - printing money to two decimal places

### ISSUE THREAD

**Issue by FiddlersCode** [makersacademy/problem-solving#16]
`def format_money(amount)
  puts "$#{amount.to_f}"
end

format_money(33.99)
format_money(3)`

Hi all, I'm doing the following kata: https://www.codewars.com/kata/dollars-and-cents/train/ruby

I am stumped on how to add a trailing zero.  .to_f will add one zero but it makes "3" "3.0" not "3.00".  Obviously this is a common problem (writing money in Ruby) but Google led me to many dark places so I'm hoping one of you clever folk can help.

tootles
Paula

**Comment by FiddlersCode** [comment]
Solved thanks to @startuprob 
def format_money(amount)
  puts '$%.2f' % amount
end


format_money(33.99)
format_money(3)

**Comment by nikeshashar** [comment]
What happens if you remove the `puts` from inside the method?

**Comment by FiddlersCode** [comment]
Yeah, I removed the puts to make it pass the code wars test :)

**Comment by nikeshashar** [comment]
Nice. It's good to try *not* to have `puts` statements inside of methods.

**Comment by AlexChalk** [comment]
@pmuldoon86 How does this work? Especially the `2f` bit? I mean I can see it sets two floating digits, but what are the rules more generally with that sort of format specification?

**Comment by FiddlersCode** [comment]
To be honest, I'm not sure - I really struggled to find hard info on that format specification!

**Comment by nikeshashar** [comment]
I had a quick google - found some interesting stackoverflow docs + a codecademy thing about `.2f`. 

There's other ways of doing the same thing too!

**Comment by AlexChalk** [comment]
Yeah, my solution was far less elegant though, which I understand is not the ruby way.
