### ISSUE TITLE
Chapter 8 Question 1 

### ISSUE THREAD

**Issue by darciew** [makersacademy/problem-solving#160]
Not sure how to match the values to the users word and add them all together?

At the moment it is just printing out the word...

<img width="383" alt="screen shot 2018-08-21 at 13 35 28" src="https://user-images.githubusercontent.com/31215123/44401616-1b0e8e80-a547-11e8-8eab-aca774164f6c.png">
<img width="349" alt="screen shot 2018-08-21 at 13 35 49" src="https://user-images.githubusercontent.com/31215123/44401633-23ff6000-a547-11e8-8064-756dc624bbc4.png">

Any ideas on where I am going wrong?

**Comment by afaraone** [comment]
It looks like the strings in `word` are lower case. Does it work with upper case?

**Comment by jonurry** [comment]
Hi Darcie,
There's no need to iterate over the points hash.
you already know the letter, so to get the points value for that letter you can say:
points[letter]
Also, afaraone is correct. You need to be using upper case letters or converting them to upper case before accessing the hash keys.

**Comment by darciew** [comment]
thanks both :)

<img width="349" alt="screen shot 2018-08-21 at 14 09 31" src="https://user-images.githubusercontent.com/31215123/44403254-df29f800-a54b-11e8-943e-557c0df4d2de.png">

That seemed to do the trick now I am just left with the values printed - do I use sum to add them all up?

**Comment by jonurry** [comment]
you can keep a running total in a variable (increment the total score for each letter) and output the total score at the end

**Comment by darciew** [comment]
thanks @jonurry!
