### ISSUE TITLE
Chapter8 question2

### ISSUE THREAD

**Issue by emmaalbury** [makersacademy/problem-solving#161]
I'm stuck on the first bit of this question. So far I'm attempting to make two new hashes, one for sport, one for fruit. I'm focusing on the sport hash first (I can copy the code for the fruit hash). I'm currently trying to push the names as values to the correlating sport key. I'm following the same procedure used in the Hash chapter course notes (the sports/names program down the bottom of the page). But mine isn't getting the right outputs. I'm getting an error saying "undefined method `push' for nil:NilClass (NoMethodError)". I tried .push(player_key) and got the same error. What's going on? Thanks

![screen shot 2018-08-22 at 2 33 30 pm](https://user-images.githubusercontent.com/25674795/44467138-08b15500-a61a-11e8-8756-81836e23a41f.png)

**Comment by emmaalbury** [comment]
same when using sport_type[sport_key].push(player_key)
![screen shot 2018-08-22 at 2 49 52 pm](https://user-images.githubusercontent.com/25674795/44467411-bcb2e000-a61a-11e8-917d-c08df214ad0c.png)

**Comment by djstephenson7** [comment]
Bear in mind that 'people' is an array of hashes. 
Presently, you're iterating over 'people' with 'people.each' and treating it like a hash (I made the same mistake).
Try iterating over the array, then iterating again over the keys and values.

**Comment by emmaalbury** [comment]
Thanks Daniel!
