### ISSUE TITLE
chapter 6 question 3

### ISSUE THREAD

**Issue by jlrodney** [makersacademy/problem-solving#162]
Hi,
Does anyone know why my program exits when I input south in the second while loop rather than change the location back to location 1.
Thanks
![screen shot 2018-08-23 at 14 27 27](https://user-images.githubusercontent.com/42071451/44528316-24336300-a6e1-11e8-8187-0f3d95552604.png)

**Comment by NadiaAiraf** [comment]
Hey the issue you're having is due to having 2 different while loops going on. When you put south in the second while loop and it loops back up to the top then location == 1 and so the loop ends.

You should be able to do it all within just one loop

**Comment by jlrodney** [comment]
Yes I see! I have sorted that now.
Many thanks
