### ISSUE TITLE
Chapter 9

### ISSUE THREAD

**Issue by djstephenson7** [makersacademy/problem-solving#163]
Hi guys,

I'm a little stuck on what I should do next with my code. I have almost all the methods I need to write for the question, but I don't know how to link them together in the run_game method.

![screen shot 2018-08-23 at 18 10 01](https://user-images.githubusercontent.com/41509062/44540885-37096000-a700-11e8-94e4-25addb13b564.png)

**Comment by m-rcd** [comment]
Hi, try to write run_game from the perspective of the dealer. So the first thing the dealer would do is tell the player to make a move. Then based on that move, the dealer will draw a random card . Then another move etc.At every card dealt, the player will be told what the score is so far, and asked what they want to do. At some point, the dealer and the player will know that the player is bust and the game will be over . The player can also stick at any time and end the game .
I'm sorry if this is cryptic , I tried not to give you the answer :) Let me know if you have any trouble

**Comment by djstephenson7** [comment]
Hi guys, has anyone else had this issue? My code is working and I'm trying to run the rspec tests, but for some reason, it's running the code instead?

![screen shot 2018-08-25 at 11 30 40](https://user-images.githubusercontent.com/41509062/44617453-54524180-a85a-11e8-930a-96ebdadd5e03.png)

**Comment by m-rcd** [comment]
Hey, it's hard to say without looking at your code but it could be because you have an infinite loop. Hope that helps :)

**Comment by djstephenson7** [comment]
Can you tell by looking at it? 
![screen shot 2018-08-25 at 11 34 04](https://user-images.githubusercontent.com/41509062/44617476-d93d5b00-a85a-11e8-8ec8-be9d0d8dea34.png)

**Comment by camjw** [comment]
The "Hit or stick" prompt appears because rspec has to run your code to test it and the last line of your code actually runs the game. If you just comment out the run_game line then it should be okay.

**Comment by djstephenson7** [comment]
I've deleted the last line and run the test again and this is the result. Baffled here
![screen shot 2018-08-25 at 11 42 18](https://user-images.githubusercontent.com/41509062/44617539-03434d00-a85c-11e8-92b7-1f32353af381.png)

**Comment by NadiaAiraf** [comment]
Hey daniel, I think you've got an infinite loop in the **move** method that occurs when someone types in a word that isn't "hit" or "stick"

**Comment by djstephenson7** [comment]
Cheers guys, all sorted now
