### ISSUE TITLE
Chapter 9

### ISSUE THREAD

**Issue by alakijaayo** [makersacademy/problem-solving#165]
Having an issue passing the final part of the run code. I am getting 3 failures, with the failure telling me:

Failure/Error:
       expect { run_game }
         .to output(/#{expected_output}/m).to_stdout
     
     NoMethodError:
       undefined method `<=' for nil:NilClass

For the last three questions. Any ideas?

**Comment by T-Miller0** [comment]
I am fairly certain that it means, it cannot perform <= when the value is nil. I had a similar issue this morning. I hope that helps?
