### ISSUE TITLE
Chapter 8 question 2

### ISSUE THREAD

**Issue by T-Miller0** [makersacademy/problem-solving#166]
Hey Guys, Im not really sure where to go from here. Any ideas?

![screenshot 18](https://user-images.githubusercontent.com/42030623/44620725-63a0b180-a891-11e8-8efa-2a32a1b743b5.png)

**Comment by afaraone** [comment]
Ok, I'll give you a couple of things to help you work it out. 
This exercise requires two pieces of input from the user, the category name and the value. You only use `gets` once in line 36 for the category.
Secondly, you should use indentation. Anything inbetween `if` and `end` should be indented, likewise for `do` and `end`. This will help you work out how your code is working.
Finally, I think you need to try and break down the problem and simplify it. Right now, your code is assuming that the user will select `"sport"` as the category.
As I see it the exercise wants you to do the following:
The user inputs a category and a value, let's say `"fruit"` and `"kiwi"`. The program should look through the `people` array, find the hashes where the value for the key `"fruit"` is equal to `"kiwi"`. It should then print out the value for the key `"name"` of those relevant hashes.

**Comment by T-Miller0** [comment]
![screenshot 20](https://user-images.githubusercontent.com/42030623/44621027-06a7fa00-a897-11e8-86c4-db5202efbbbf.png)

**Comment by T-Miller0** [comment]
![screenshot 21](https://user-images.githubusercontent.com/42030623/44621031-0dcf0800-a897-11e8-8328-8cc8ced2daf4.png)

**Comment by T-Miller0** [comment]
I'm not sure why the errors are occurring

**Comment by AnastasiiaBlaha** [comment]
I think you’re overthinking too much. You don’t need that much. You have category and value you need to get from the user using gets.chomp which you did at the beginning. Perfect! And then you need your program to go through people array (.each) and see if the user’s input of category is equal to any user’s value in the array. When a user enters the category and then the value, the program should puts the name(s) of people who are in the same category and value.
