### ISSUE TITLE
Chapter 10

### ISSUE THREAD

**Issue by djstephenson7** [makersacademy/problem-solving#168]
Hi guys,

My program appears to be working fine, but it isn't passing the spec tests. Although it returns the list when I run the program, the spec returns the address where the object is stored like this:

![screen shot 2018-08-26 at 13 34 39](https://user-images.githubusercontent.com/41509062/44628306-edee2180-a934-11e8-96fb-5c42ae182e16.png)

Here is a screenshot of my code:

![screen shot 2018-08-26 at 13 35 20](https://user-images.githubusercontent.com/41509062/44628308-f2b2d580-a934-11e8-909d-36c42152457e.png)

**Comment by cristinaocanamanzano** [comment]
Hi! In the add method, I think you do not need to create a new todo object, you just need to push "items" into the list. Could you try that?

**Comment by djstephenson7** [comment]
Yeah, the rspec error is this:

![screen shot 2018-08-26 at 13 56 18](https://user-images.githubusercontent.com/41509062/44628461-f300a000-a937-11e8-84ff-78bbcb03aa39.png)

And the ruby error is this:

![screen shot 2018-08-26 at 13 56 45](https://user-images.githubusercontent.com/41509062/44628473-1c213080-a938-11e8-9233-4d28c071ae1b.png)

**Comment by AntonioDaria** [comment]
Daniel, i can see two problems to begin with:
1. In the add method as Cristina mentioned all you need to do is to push the items to the list.
2. There are a bunch of instruction outside your methods at the end which shouldn't be there (i.e. list.add , list.print and so on)
The arguments are passed by the tests in the rspec files.
So i would say fix these 2 things first and try to run it again and let me know

**Comment by djstephenson7** [comment]
Hi guys,

This is the issue now:

![screen shot 2018-08-26 at 15 45 48](https://user-images.githubusercontent.com/41509062/44629431-2ac31400-a947-11e8-885c-06b9308d105a.png)

Same as the issue I had with question 9

**Comment by ShinyVerse** [comment]
Your error is that it's not printing the text from the todo, it is printing the id of the created todos. Check your methods one by one and make sure the information you get back is what you are wanting to use. 

The specs will be creating a newtodo = Todo.new("With a message")
Creating a newList = TodoList.new()
And then it will be adding in the new todo. newList.add(newtodo)
You shouldn't need to call Todo.new() in your TodoList class.

**Comment by djstephenson7** [comment]
Thank you all!
