### ISSUE TITLE
Unable to load repo to Github 

### ISSUE THREAD

**Issue by JakePEGG** [makersacademy/problem-solving#172]
So i'm getting this error when trying to upload my repo to GitHub:

$ git push -u origin master
ERROR: Permission to makersacademy/playing-with-git.git denied to JakePEGG.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I have already added my SSH key to my account, I have tested my connection and it's successfully authenticated so not sure what to do here. Been stuck on this since yesterday and haven't been able to go past lesson 43. Any advice would be greatly appreciated.

**Comment by nkhil** [comment]
Hi @JakePEGG 

Have you forked this repo before cloning it? 

If you cloned the repo directly from makersacademy and are trying to push to it, it is rightly saying that you don't have the correct access rights (because the repo belongs to makersacademy). 

EDIT: You might also want to check `git remote -v` to see if you've set the origin correctly. If not, this might be helpful: https://help.github.com/articles/adding-a-remote/

**Comment by JakePEGG** [comment]
Hi @nkhil 

When doing the git remote -v i get: 
$ git remote -v
origin  git+ssh://github.com/user/repo.git (fetch)
origin  git+ssh://github.com/user/repo.git (push)

I'll try deleting the existing remote as instructed in that link. Will come back to you shortly.

**Comment by JakePEGG** [comment]
I created a new one and now encounter this error:

$ git push -u origin master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

any ideas?

**Comment by nkhil** [comment]
I'm not 100% sure what the issue could be. I found a couple of URLs that might help you troubleshoot. 

https://help.github.com/articles/error-permission-denied-publickey/

https://stackoverflow.com/questions/13509293/git-fatal-could-not-read-from-remote-repository

(FWIW, I struggled setting up Github a few months ago too so I feel your pain. Hopefully you're able to solve this soon)

**Comment by JakePEGG** [comment]
Cheers mate, appreciate this. Will look into these now!
