### ISSUE TITLE
Kata - Are they the "same"?

### ISSUE THREAD

**Issue by baree99** [makersacademy/problem-solving#18]
Hi girls and lads

I got a tiny lil issue I have no idea how to solve. The exercise is: [Kata - Are they the "same"?](https://www.codewars.com/kata/550498447451fbbd7600041c/solutions/ruby)

My solution would be:

```
def comp(array1, array2)
  array1.sort == array2.sort.collect { |a| a ** 0.5 }
end 
```

I am passing the tests, but got an error message when I am "attempting".

The error message:

```
comp': undefined method `sort' for nil:NilClass (NoMethodError)
	from `block in'
	from `block in describe'
	from  `measure'
	from  `describe'
	from  `
```

Thanks for any help

**Comment by nikeshashar** [comment]
Try not to put Links in backticks

[Square brackets for text](www.curlybracketsforlinks.com)

`One backtick should be code`

```
3 backticks should be 
multi line
code
```

**Comment by nikeshashar** [comment]
Edits :

Hi girls and lads

I got a tiny lil issue I have no idea how to solve. The exercise is: [Kata - Are they the "same"?](https://www.codewars.com/kata/550498447451fbbd7600041c/train/ruby)

 My solution would be: 
```
def comp(array1, array2)`
  array1.sort == array2.sort.collect { |a| a ** 0.5 }`
end
```

I am passing the tests, but got an error message when I am "attempting".

The error message:

```
comp': undefined method `sort' for nil:NilClass (NoMethodError)
	from `block in'
	from `block in describe'
	from  `measure'
	from  `describe'
	from  `
```

Thanks for any help

**Comment by nikeshashar** [comment]
@baree99 - edit my message above to see the differences in syntax for Markdown

**Comment by AlexChalk** [comment]
@baree99, the problem goes away for me if I call `collect` _before_ `sort`. I'm not sure why it makes a difference though.

**Comment by JayWebDevCom** [comment]
I think  it's because the Codewars tests include blank arrays.
So comparison of nil values will result in that error.

```
def comp(array1, array2)
 if (!array1.nil? && !array2.nil?)
  array1.sort == array2.sort.map { |i| i = Math.sqrt(i) }
  else
  return false
  end 
end
```

**Comment by baree99** [comment]
@nikeshashar thanks, I updated it
@adc17 for me that didn't work - thanks for your reply though
@JayWebDevCom thanks, I didn't think about that, it did work 👍
