### ISSUE TITLE
LRTHW: Exercise 40 - why the parentheses?

### ISSUE THREAD

**Issue by will-gant** [makersacademy/problem-solving#19]
Hiya

Something has been confusing me in exercise 40 of 'Learn Ruby the Hard Way'. Although I've just finished the exercise, I don't understand the use of brackets on lines 7, 19, and 21:

![screenshot 2017-03-23 at 20 12 19](https://cloud.githubusercontent.com/assets/20523607/24266020/b19bb90a-1005-11e7-864f-331b3ee65ea2.png)

Because I wanted to see what difference they made, I deleted them and then ran the program again... and it was exactly the same. Methods don't need to take parameters, and can be written without them, right? If so, why might an empty space have been left for one (if that's what this is)?

Thanks!

**Comment by TimRobinson1** [comment]
I think it's just considered good practice to include parenthesis with the methods, even if you're not supplying a parameter, I don't think there's technically a practical difference between including them or not.

**Comment by danielemanuel** [comment]
There is no problem if  you have them or not, as long as they are empty.

**Comment by nikeshashar** [comment]
We follow a this Ruby style guide : https://github.com/bbatsov/ruby-style-guide. General convention is always use parenthesis' if there is a parameter/arg to pass into the method. If the method doesn't have an parameter/arg then no need for them. Hope that helps

**Comment by will-gant** [comment]
Great, thank you!
