### ISSUE TITLE
Lesson 45 - Pulling code from Github

### ISSUE THREAD

**Issue by will-gant** [makersacademy/problem-solving#2]
Hi! After entering the command 'git pull' on my console (inside the directory that is my git repository), I receive the following message:

"_Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository._

_Please make sure you have the correct access rights
and the repository exists._"

Apparently I _should_ be seeing "_Already up-to-date_". A bit stumped as to what to do next, as I've already taken the SSH key from id_rsa.pub and put that into Github, and am able to use the commands 'git push' and 'git log' (these are shown higher up in the screenshot below).

I'm using the console on ide.c9.io. Would be mega grateful for a nudge in the right direction! Thanks.

![screenshot 2017-03-15 at 11 59 13](https://cloud.githubusercontent.com/assets/20523607/23945460/df0b6a7e-0976-11e7-9a3a-b25934e1c651.png)

**Comment by adc17** [comment]
HI @bruxelles86 , I'm pretty sure that pushing to your repository requires your private key!

**Comment by AlexChalk** [comment]
Hi @bruxelles86, I would check out this page: https://help.github.com/articles/error-permission-denied-publickey/

**Comment by BertZZ** [comment]
I got the same error when using  git push -u origin master
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Did you find a solution to this yet?

**Comment by ns-winter** [comment]
Did you guys first create your workplace/project  on c9.io or did you first create a repository on GitHub?

**Comment by BertZZ** [comment]
Well I've been working through the Pre Course material using c9.io so that came first then the GitHub repository

**Comment by ns-winter** [comment]
Ok sorry just making sure I wasn't way off-base. 

I think I'd followed the steps on this site and it had gotten it to work for me (think swe'd have done some of the steps as part of the pre-course) :-

http://lepidllama.net/blog/how-to-push-an-existing-cloud9-project-to-github/

I think the 6th point is fairly crucial...

**Comment by BertZZ** [comment]
I managed to get  git push -u origin master to work by starting from the beginning with my SSH Key, I think i missed  ssh-add ~/.ssh/id_rsa last time.

**Comment by will-gant** [comment]
Sorted! This was because I was using the 'public' key instead of a private one. Thanks.
