### ISSUE TITLE
Kata - sorting array of arrays

### ISSUE THREAD

**Issue by FiddlersCode** [makersacademy/problem-solving#20]
Hi all,

Working on this kata https://www.codewars.com/kata/same-array/train/ruby and have a problem sorting an array of arrays - I can't figure out how to sort over the array of arrays.  This code works with comparing two arrays.  (And yes, I know I have some unnecessary variables [arr1, arr2] - that was just so I could keep track of some stuff in the code.)

Thanks!

```
def same(arr_a, arr_b)
  arr1 = arr_a.sort
  arr2 = arr_b.sort
  puts arr1
  puts arr2
  if arr1 == arr2
    return true
  else
    return false
  end
end

puts same([[2,5,], [3, 6]], [[2,5], [6,3]])
puts same([2,5,9], [2,9,5])

```

**Comment by JayWebDevCom** [comment]
So you can flatten before you sort i.e. make a 2d array of arrays into a single array

```
def same(arr_a, arr_b)
  arr1 = arr_a.flatten.sort
  arr2 = arr_b.flatten.sort
  #puts arr1
  #puts arr2
  if arr1 == arr2
    return true
  else
    return false
  end
end
```

Then shorten it to

```
def same(arr_a, arr_b)
    arr_a.flatten.sort == arr_b.flatten.sort
end
```

Or compare the two arrays in place without flattening. 

```
def same(arr_a, arr_b)
    arr_a.map{ |i| i.sort }.sort == arr_b.map { |i| i.sort }.sort
end
```

**Comment by FiddlersCode** [comment]
@JayWebDevCom cheers!  The first two work great, but I get a method error for the last one on .sort and I'm also not quite sure how this is meant to work.  

![image](https://cloud.githubusercontent.com/assets/7489685/24289264/6ba60b62-1078-11e7-814e-4585cc679e17.png)

**Comment by Yorkshireman** [comment]
@pmuldoon86 Hey dude my advice for this is always read the stack trace carefully. Generally when you're starting out the usual reaction is just "WTF?!" and run away without reading it properly and just try something else randomly and see if it works, rinse and repeat.

The more you develop though the more valuable you realise the stack trace is and the more comfortable you become with it. So, for example, `undefined method 'sort' for 2:Integer` - have a think about what that might be telling you and google "Ruby sort" and see what you find. Post your findings here!

**Comment by FiddlersCode** [comment]
@Yorkshireman It's like you see into my mind...  Thanks!

**Comment by AlexChalk** [comment]
Also, copying and pasting the code with formatting
```
like this
and this
and this
```
is much easier for the rest of us to read on here ;)
