### ISSUE TITLE
Inefficient code failing two katas

### ISSUE THREAD

**Issue by will-gant** [makersacademy/problem-solving#21]
Hi folks

I've hit a brick wall with two codewars katas (both 7 kyu). Although in both cases I've come up with solutions which pass all the examples, codewars always gives me this message:

> Process was terminated. It took longer than 12000ms to complete
> 
> Why did my code time out?
> Our servers are configured to only allow a certain amount of time for your code to execute. In rare cases the server may be taking on too much work and simply wasn't able to run your code effectiently enough. Most of the time though this issue is caused by inefficient algorithms. If you see this error multiple times you should try to optimize your code further.

1. The first Kata is '[Sum of the first nth term of Series](https://www.codewars.com/kata/sum-of-the-first-nth-term-of-series/train/ruby)', which asks you to write a function which returns the sum of following series up to the nth term(parameter): 1 + 1/4 + 1/7 + 1/10 + 1/13 + 1/16 +.

Here is my code: 

```
def series_sum(num)
  current_num = 1
  
  top_num = 1.to_f
  bottom_num = 4.to_f
  answer = 0.to_f
  final_num = num
  
  while current_num != final_num.to_i
    current_num += 1
    
    fraction = top_num / bottom_num
    
    answer = answer + fraction
    
    bottom_num += 3
    
  end
  
return '%.2f' % (answer + 1)

end
```

2. The second Kata is '[Growth of a Population](https://www.codewars.com/kata/growth-of-a-population)'. Your method has to take four parameters, for starting population, % annual natural growth, annual inward migration, and final population. The method must return the number of years needed to rise to (or above) the final population from the starting population. Here's my code:

```
def nb_year(p0, percent, aug, p)
    year_counter = 0
    current_population = p0
    population_goal = p
    migration = aug
    
    if percent.to_i > 0
        increase = 1.to_f + (percent / 100.to_f)
    else 
        increase = 1.to_f - (percent / 100.to_f)
    end
    
    until  current_population >= population_goal
        year_counter += 1
        current_population *= increase
        current_population = current_population.to_i
        current_population += migration
            
    end
    return year_counter
end
```

Grateful for any observations. Thank you!

**Comment by adc17** [comment]
@bruxelles86 Are you saying you get "tests passed" and the error?

**Comment by AlexChalk** [comment]
Hmm, number 1 might be failing this test if it exists: `Test.assert_equals(series_sum(0), "0.00")`
current_num (1) != final_num (0), and in that scenario it will loop infinitely, as you have told it to keep adding to current_num.

**Comment by AlexChalk** [comment]
For number 2, it's also a zero problem. These lines 
```
if percent.to_i > 0
        increase = 1.to_f + (percent / 100.to_f)
    else 
        increase = 1.to_f - (percent / 100.to_f)
    end
```
will reduce any percentage of 0-1% (e.g. 0.25%) to 0, and then start multiplying `current_population` by a value <1 (which will keep lowering it). You'll therefore never get `current_population` up to the required `final_population` value, and you have another infinite loop on your hands. 

I think you can replace that if statement with a simple ` increase = 1 + (percent / 100.to_f)`, as the instructions state that the `percent` value will always be positive.

**Comment by will-gant** [comment]
Thank you lots! That second one has got me through the population Kata. Now I'll try the first...

**Comment by will-gant** [comment]
Perfect - you were right about the first one too!
