### ISSUE TITLE
Ruby Kickstart 3:14

### ISSUE THREAD

**Issue by AlexChalk** [makersacademy/problem-solving#24]
Hi all, I'd appreciate a heads up on where I'm going wrong below. To my eyes it looks like this code should work.

I'm trying to solve the problem described here: https://github.com/JoshCheek/ruby-kickstart/blob/master/session3/challenge/14_var_args_and_hash.rb

The relevant info: my methods should correctly count the no. of chains of 2+ identical digits when multiple digits are passed in with a final param of `:problem => :count_clumps`. 

i.e. `problem_14(1, 2, 2, 2, 2, 3, 4, 4, :problem => :count_clumps)` should return `2`, as it contains 2 chains of 2+ identical digits.

I'm failing an rspec test for the following:
`problem_14(1, 2, 2, 3, 4, 4, :problem => :count_clumps)`
My methods should return `2`, but they return `0`.

I think the problem is with whatever `problem_14` is passing to `count_clumps`. `count_clumps` passes rspec tests when tested directly, but returns the wrong result when invoked via `problem_14`.

```
def problem_14(*parameters)
  if parameters[-1].is_a?(Hash)
    parameters.pop[:problem] == :same_ends ? same_ends(parameters) : count_clumps(parameters)
  else
    count_clumps(parameters)
  end
end

def same_ends(n, *array)
  return true if n == 0
  array[0..n-1] == array[-n..-1]
end

def count_clumps(*array)
  count = 0
  clump = false
  array.each_index do |x|
    if array[x] == array[x+1]
      clump = true
    else
      count += 1 if clump
      clump = false
    end
  end
  return count
end
```

Any help is greatly appreciated. Thanks all.

**Comment by JayWebDevCom** [comment]
I think that here

```
def count_clumps(*array)
  count = 0
  clump = false
  array.each_index do |x|
    if array[x] == array[x+1]
      clump = true
    else
      count += 1 if clump
      clump = false
    end
  end
  return count
end
```

`count` will never go up because `clump` will never be true due to your if-else separation.

**Comment by AlexChalk** [comment]
Hmm, that's not the problem—the method works fine when tested in isolation, e.g. see the image below where I've plugged it into a repl:

<img width="1063" alt="capture d ecran 2017-03-25 18 46 30" src="https://cloud.githubusercontent.com/assets/22868730/24326746/8e1eadca-118b-11e7-95f3-4bbb2a82d4d6.png">

**Comment by JayWebDevCom** [comment]
`count_clumps(1,2,2,2,2,3,3,3,4,5,5)`
vs
`count_clumps([1,2,2,2,2,3,3,3,4,5,5])`
perhaps?
you're right. the * should have taken care of that.

**Comment by AlexChalk** [comment]
Thanks, good spot, it fails in the second format. Now I just need to figure out why :p

**Comment by AlexChalk** [comment]
Maybe if you pass a `*parameter` an array, it's saved as an array inside an array?That would return zero. 
I suspect that's what happened. `array.flatten!` seems to fix it!

**Comment by JayWebDevCom** [comment]
and always call 
`count_clumps(*array)`
in some places you have 
`count_clumps(array)`

**Comment by AlexChalk** [comment]
You're right—so that makes sure they're sent as a list of parameters instead of as an array?

**Comment by JayWebDevCom** [comment]
I think so. 
if you send an array to (*array) your array will end up inside of an array.
which is why you cleverly flattened.
just also to be consistent.

**Comment by AlexChalk** [comment]
Sure, your way is much neater. Thank you. It's frustrating/good to know I was a few `*`s away from getting this right.

I'll close the issue now.
