### ISSUE TITLE
Error in LRTHW exercise 17 i dont understand

### ISSUE THREAD

**Issue by BertZZ** [makersacademy/problem-solving#25]
In the exercise, the comment on line 5 says that we can consolidate lines 6 and 7 into one line, which I have attempted to do in my code so that it reads as such:
`from_file, to_file = ARGV

puts "Copying from #{from_file} to #{to_file}"

in_file = open(from_file).read

puts "The input file is #{in_file.length} bytes long"

puts "Does the output file exist? #{File.exist?(to_file)}"
puts "Ready, hit RETURN to continue, CTRL-C to abort"
$stdin.gets

out_file = open(to_file, 'w')
out_file.write(in_file)

puts "Alright, all done"

out_file.close
in_file.close`

However when I run thi I get the error "ex17.rb:21:in <main>': undefined methodclose' for "This is a test file.\n":String (NoMethodError)
Did you mean? clone"

I can only assume the reason for this error is something to do with the way I typed in_file = open(from_file).read. Can anyone confirm this and if so how do I write this on a single line

**Comment by JayWebDevCom** [comment]
It should be

`indata = open(from_file).read`

**Comment by BertZZ** [comment]
Then do I just replace all instances of in_file with indata so that the last line then becomes indata.close? Because surely that creates the same issue.

**Comment by JayWebDevCom** [comment]
the data is referred to through variable `in_file`
but the file to close is not`in_file` but `from_file`

**Comment by JayWebDevCom** [comment]
Sorry for any confusion.
you do not need to close `in_file`
`in_file` just holds the data. it is not a file object.

**Comment by BertZZ** [comment]
So the line is irrelevant? Its at the end of the exercise in the book but your saying it doesn't need to be there?

**Comment by JayWebDevCom** [comment]
he has
`in_file = open(from_file)`
you have
`in_file = open(from_file).read`

so he closes `in_file`

**Comment by BertZZ** [comment]
Ok but if you do it in one line like the comment suggests you dont need to close in_file?

**Comment by JayWebDevCom** [comment]
if you do it on one line, you do not have an _inbound_ file object that you opened so you do not need to close it.
Close the outgoing file object though.

**Comment by BertZZ** [comment]
Ok thanks for your help :)
