### ISSUE TITLE
ruby-kickstart session 3 challenge 13

### ISSUE THREAD

**Issue by ffasolin** [makersacademy/problem-solving#27]
I'm trying to get this code to work for this one but it's not calling the block when one is given. Can anyone see what I'm missing?
```

def your_sort (arr, final_arr=[], &block)
  if block == true
    arr.map(&block)
  elsif arr.length == 0
    final_arr
  else
    arr.each { |i| final_arr << i if i == arr.min }
    arr.delete(arr.min)
    your_sort(arr, final_arr)
  end
end
```

![screen shot 2017-03-26 at 23 55 45](https://cloud.githubusercontent.com/assets/25456821/24336006/e01b7532-127f-11e7-9844-6fad03c4129c.png)

**Comment by JayWebDevCom** [comment]
It seems to works with `sort` not `map`
and `== true` seems to be complicating things.

```
def your_sort (arr, final_arr=[], &block)
  if block #== true
	     arr.sort(&block)
  elsif arr.length == 0
    final_arr
  else
    arr.each { |i| final_arr << i if i == arr.min }
    arr.delete(arr.min)
    your_sort(arr, final_arr)
  end
end
```

**Comment by AlexChalk** [comment]
@ffasolin, I don't think the method is meant to provide a map for the array. Look at the examples in kickstart—all the blocks take two parameters, and then use the `<=>` notation to report how the array should be ordered. 

Your method needs to accommodate that structure, i.e. for a start I think it needs to contain a call to the block, in which the block is assigned two parameters. Which two parameters? That depends on the sorting algorithm you have decided to implement, but I think you'll have to iterate, i.e. call the block multiple times with multiple pairs of parameters.

I suggest you implement your sorting algorithm first, then think about how it could be adapted to accommodate the block. Hope that helps, and sorry I can't suggest something more concrete.

**Comment by ffasolin** [comment]
Yes, that is right. I realised that after Jaiye suggested I used sort instead of map, which works but defeats the point of the exercise. I'll share it once I make it work. Thanks for looking into this Jaiye and @adc17 !

**Comment by AlexChalk** [comment]
@ffasolin, I think you have to implement `sort` yourself, and do it in a way that includes some kind of `if` statement like 
```
      if x > y
         x, y = y, x
      end
```
Once you've got that, you can adapt it to work with `<=>` and with custom sorting parameters.

**Comment by ffasolin** [comment]
Finally closing this:

```
def your_sort(arr, &block)
  block = block if block
  block = lambda {|a, b| a <=> b} if !block
    arr.length.times do
      for n in 0..arr.length-2 do
        if block.call(arr[n], arr[n+1]) > 0
          arr[n], arr[n+1] = arr[n+1], arr[n]
	end
      end
    end
    arr
end
```

Thanks for the help, guys!
