### ISSUE TITLE
Week 3 | Exercise 8 | Number 4 (Using While/Until Loops)

### ISSUE THREAD

**Issue by G9A2HvK9** [makersacademy/problem-solving#28]
I'm having some issues trying to get all names in the array printed to the console (with cohort etc) using the while/until loops. The .each iterator works really well but I can't seem to sort out of the loops functionality for this purpose.

**Comment by AlexChalk** [comment]
@G9A2HvK9, what are you using at the moment? Paste in your best attempt.

**Comment by G9A2HvK9** [comment]
Got the issue sorted with some hope. will post below. But beware the spoilers ;)

`def print_names1(students)
    i = 0
    until i == students.count
      puts "#{students[i][:name]} (#{students[i][:cohort]} cohort)"
      i += 1
    end
  end`

**Comment by AlexChalk** [comment]
Yup, that's just a better version of mine (`until` is much tidier)
```
index_count = 0
  while index_count <= students.length-1
     puts "#{index_count+1}. #{students[index_count][:name]} (#{students[index_count][:cohort]} cohort)"
     index_count += 1
  end
```

**Comment by G9A2HvK9** [comment]
Haha. I really don't know what I'm doing with the formatting here :P

**Comment by AlexChalk** [comment]
Use three backticks either side of your code block to get it like mine.
