### ISSUE TITLE
Greatest Common Divisor

### ISSUE THREAD

**Issue by AlexChalk** [makersacademy/problem-solving#29]
Hi, the below code should find the largest number that divides cleanly into `x` and `y`.
The below code loops infinitely when `x = 8` and `y = 9`, but we can't spot why. Can anyone help:

```
def mygcd(x, y)
  x, y = y, x if x > y
  i = 1
  loop do
    next if !(x % i == 0)
    return x/i if (y % (x/i) == 0) && (x % (x/i) == 0)
    i += 1
  end
end
```

**Comment by michaelbjacobson** [comment]
Hi @adc17, I realise this question is pretty old now and therefore you've probably already sorted the issue but I thought I'd share my `euclidean` method just incase anyone else has been having difficulty with this. This method will return the greatest common divisor of `a` and `b`.

```
def euclidean(a,b)
  if (a % b).zero?
    b
  else
    euclidean(b, a % b)
  end
end
```

**Comment by AlexChalk** [comment]
Hi @michaelbjacobson, I did find a solution to this on wikipedia, but my question was more specifically why the above code loops. Btw, I think codewars actually told me the euclidean method was too inefficient! Thanks in any case.

**Comment by anitacanita** [comment]
@adc17 Can you share what the solution was and close the issue? Thanks 👍

**Comment by AlexChalk** [comment]
I didn't get a solution to my question—I don't understand why the code is looping! But I guess it's been so long I'm unlikely to hear anything now.
