### ISSUE TITLE
clmystery Step6 - how to search for multiple keywords in one file

### ISSUE THREAD

**Issue by saralynnazuk** [makersacademy/problem-solving#3]
I'm really struggling with this step and would appreciate any help you can give! I know how to find each individually but I'm not sure how to search for license plate / car model / car colour / suspect's height all at the same time (if this is indeed what we're being asked to do). 
By using 

$ grep -A 5 L337 vehicles > suspects.txt

I ended up with 13 potential suspects in my suspects.txt file and I could, from there, whittle it down visually by eliminating those that don't match the other known clues but I don't think that's how we're supposed to do it so can someone please show me the right way?

**Comment by ns-winter** [comment]
I'm at work but from memory I think I had done something on the lines of:

$grep -A 5 L337 vehicles | grep -C 5 Blue | (more grepping with other words) > suspects.txt

So piping the results from each (using grep -C to keep both lines above and below the current grep).

**Comment by ns-winter** [comment]
Let me know if that makes sense 😊

**Comment by AlexChalk** [comment]
You can also use `grep -B number_of_lines`, to get matches plus lines above the match.
e.g. `grep -B 1` will give you two lines for each hit, the matching line and the line above it.

**Comment by saralynnazuk** [comment]
Thanks, @ns-winter - you're a star! I was able to figure it out with the guidance you gave. Now I just have to hope I did the pull request bit right 🤞

**Comment by henryhobhouse** [comment]
Hi All, 

I have this completed to the extend the results are usable however they are showing snippets from other patterns which don't have all the requirements with the grep parameters. I used:

> grep -A 5 L337 ./mystery/vehicles | grep -C 5 Honda | grep -C 5 Blue | grep -C 5 '\<6'

and got:

Height: 6'4"
Weight: 185 lbs
--
License Plate L337QE9
Make: Honda
Color: Blue
Owner: Erika Owens
Height: 6'5"
Weight: 220 lbs
--
--
--
Height: 6'5"
Weight: 240 lbs
--
License Plate L337539
Make: Honda
Color: Blue
--
Height: 5'3"
Weight: 198 lbs
--
--
--
Height: 6'6"
Weight: 156 lbs
--
License Plate L337369
Make: Honda
Color: Blue
--
--
License Plate L337DV9
Make: Honda
Color: Blue
Owner: Joe Germuska
Height: 6'2"
Weight: 164 lbs
--
License Plate L3375A9
Make: Honda
Color: Blue
Owner: Jeremy Bowers
Height: 6'1"
Weight: 204 lbs
--
License Plate L337WR9
Make: Honda
Color: Blue
Owner: Jacqui Maher
Height: 6'2"
Weight: 130 lbs<

Obviously sufficient to narrow down the suspects to four; the only ones with all parameters covered (6 lines). However my understanding on how this command should work is that it would remove all other patterns. Am I doing something wrong or is this a product of how grep works? Even if I could potentially give better parameters for a "cleaner" result.

**Comment by AlexChalk** [comment]
You can trim this by more closely specifying the line numbers. `-A 1` returns a match plus 1 lines below `-B 1` returns a match plus 1 lines above, and `-C 1` returns a match plus 1 line below _and_ one line above (so 3 lines total). So you can get just the details for each suspect like this:
`grep -A 5 L337 ./mystery/vehicles | grep -A 4 -B 1 Honda | grep -A 3 -B 2 Blue | grep -A 1 -B 4 "6'"`
And if you wanted just the owner, you could add another pipe: `| grep Owner`

**Comment by motri** [comment]
Hi! So I think the issue with your command is the -C bit. -C grabs both the defined number of lines before and after the pattern, so when grabbing "honda" you would wanna use -B1 and -A4 because the model of the car is in the second line of the six lines that complete the info on each driver/car combo, therefore you want to include both the line before Make: Honda (the first line -B1) the line with the pattern "Honda" and the next four (-A4). I hope I'm making sense, let me know!

**Comment by enonnai** [comment]
For further reference/explanations http://man.openbsd.org/grep

**Comment by henryhobhouse** [comment]
Ahhh. Got you. I miss-interpreted how grep -C would work with output from the previous pipe.

Thank you all!
