### ISSUE TITLE
Loading students.csv by default: Step 14 Ex2

### ISSUE THREAD

**Issue by danielemanuel** [makersacademy/problem-solving#31]
Hey guys, how did you do the second exercise of step 14? I'm curious about how to load the file by default. I guess that the method that should be changed is the one named `try_load_students`. This is my attempt so far : 
```ruby
def try_load_students
  filename = ARGV.first
   load_students  if filename.nil? 

  if File.exists?(filename) # if it exists
    load_students(filename)
     puts "Loaded #{@students.count} from #{filename}"
  else # if it doesn't exist
    puts "Sorry, #{filename} doesn't exist."
    exit # quit the program
  end
end
```

We changed line three from `return if filename.nil?` to `load_students  if filename.nil?` and we got this error: 
```shell
Roberts-MBP:student-directory robertjones$ ruby directory.rb
directory.rb:154:in `exists?': no implicit conversion of nil into String (TypeError)
	from directory.rb:154:in `try_load_students'
	from directory.rb:192:in `<main>'
```

The reason for the change was that if no argument is given on the command line we wanted to run the method `load_students`, which has a default file we want to load (`students.csv`).

**Comment by AlexChalk** [comment]
I think you want 
```
if filename.nil?
  load_students
elsif File.exists?(filename) # if it exists
  load_students(filename)
  etc.etc.etc.
```
Right now, presuming `ARGV.first == nil`, you're telling it to run `load_students` with no parameter (if it defaults to `students.csv`, that should work fine) AND then pass `nil` to `File.exists` (which won't work fine).

You need the if/elsif structure to tell ruby that if the first `if` statement is run, it shouldn't run the rest of the code.

**Comment by danielemanuel** [comment]
Yes, I did that too  before.. I'm  gonna live it like this anyway, thank you for the help mate @adc17 , appreciated
