### ISSUE TITLE
student-directory --- Exercise 8.8 --- Problem with while loop in `print(students)` method

### ISSUE THREAD

**Issue by JessicaBarclay** [makersacademy/problem-solving#32]
The `print` method isn't outputting as expected...

#=>
Students listed by cohort:            
April
1. Jessica, UK
April                       # how might I stop this line being repeated?
2. Bob, UK
April

Does anyone have any advice on how to have the cohort month outside of the while loop in the `print` method, so that it doesn't repeat (as per the screenshot of the command line). 
I am so close yet so far! Do I need a second loop..?

Thanks :)

![screen shot 2017-03-29 at 21 09 24](https://cloud.githubusercontent.com/assets/20893719/24474760/9b08bae8-14c5-11e7-9fc5-b21edf61c0b1.png)
![screen shot 2017-03-29 at 21 09 18](https://cloud.githubusercontent.com/assets/20893719/24474761/9b0fa1b4-14c5-11e7-86f9-d5ab4121806a.png)

Code as follows

`def input_students
  students = []
  puts ("_"*50)
  puts
  puts "Please enter the students information".center(50)
  puts  "To finish, just hit return twice".center(50)
  puts
  puts "Students name?".center(50); name = gets.chomp.capitalize.to_sym
    while !name.empty? do
      puts "Students cohort?".center(50) ; cohort = gets.chomp.capitalize.to_sym
      if cohort.empty? ; cohort = "N/A" end
      puts "Country of birth?".center(50) ; country = gets.chomp.to_sym
      students << {name: name, cohort: cohort, country: country}
      puts "Confirm name: '#{name}' by typing yes or no" ; typo = gets.chomp.downcase
      if typo == "no" ; puts "Students name?".center(50); name = gets.chomp.capitalize.to_sym end
      puts "Now we have #{students.count} students".center(50)
      puts "Hit return or add another name:".center(50) ; name = gets.chomp.to_sym
    end
  students
end
def print_header
  puts "The Students of Villains Academy".center(50)
  puts ("_"*50)
end
def print(students)
  i = 0
  cohort_list = students.group_by {|input| input[:cohort]}
  puts "Students listed by cohort:".center(50)
    while !cohort_list.empty? do
      cohort_list.map do |k, v|
      puts "#{k}"
      puts "#{i+1}. #{v[i][:name]}, #{v[i][:country]}"
      i += 1
    end
  end
end
def print_footer(students)
  puts "Overall, we have #{students.count} great students".center(50)
end

students = input_students
print_header
print(students)
print_footer(students)`

**Comment by JayWebDevCom** [comment]
Hi, have a look at the while loop where you define `print_students`. I think that there is a better way to write it.

**Comment by AlexChalk** [comment]
From line 29, try:
```
while !cohort_list.empty? do
  cohort_list.each do |key,value|
    puts key
    value.each do |array|
      print "#{i+1} "
      array.each_value do |v|
        print "#{v} "
      end
      puts ""
    end
  end
end
```

**Comment by AlexChalk** [comment]
@JessicaBarclay It's a bit tricky, as I think for each cohort you've got a group of hashes within an array within a hash 😝

**Comment by JessicaBarclay** [comment]
@adc17 Very tricky! Yes I'm struggling to picture that haha. The .each iteration you mentioned didn't work, the output was an integer - but perhaps another approach using each... I will let you know if I get anywhere! Thank you :)

**Comment by AlexChalk** [comment]
Ok, good luck. Also, stick three backticks on the line above and the line below your code block in the initial post ;).

**Comment by JessicaBarclay** [comment]
@adc17 Cheers yes Paula M just informed me of this aha 🙈  I'm sure I will cringe at these posts in 13 weeks!

**Comment by JessicaBarclay** [comment]
Sorted!
The `for` loop allows you to loop a condition within an each/map/select block
Thanks @adc17 and @JayWebDevCom :)

```
def print(students)
  list_by_month = students.group_by {|input| input[:cohort]}
    puts "Students listed by cohort:".center(50)
      list_by_month.map do |key, value|
        puts "#{key}"
        for index in 0..value.size-1 do
      puts "#{index+1}. #{value[index][:name]}, #{value[index][:country]}"
    end
  end
end
```
![for_loop_with_map_block_ruby](https://cloud.githubusercontent.com/assets/20893719/24479583/dcad4b78-14d7-11e7-8a66-b656063a74ee.png)
