### ISSUE TITLE
Codewars: Find All Array Values That Fall Within a Given Difference

### ISSUE THREAD

**Issue by j311y** [makersacademy/problem-solving#35]
```
class GroupByDifference
  def initialize(numbers)
    @numbers = numbers
  end
  
  def find(difference)
    x = @numbers.sort
    ans = []
    w = 0
    
    while w != @numbers.length do
      diff = x[w]-x[w+1]
        if diff <= difference
          ans << x
          w += 1
        else
          w += 1
        end
    end
    ans   
  end 
end
```
I'm getting this error:
![image](https://cloud.githubusercontent.com/assets/26009235/24718508/2fa3f6fa-1a2e-11e7-8917-c23c18dfe69b.png)

I don't understand why I can't shovel the indexs from x into my new array (ans).
Does anybody have any ideas?

**Comment by AlexChalk** [comment]
The final time this runs, it will try to do `diff = x[last_index] + x[last_index+1]` on line 12. `x[last_index+1]` is nil, and you can't add nil to anything—I think that's what's throwing the error.

**Comment by j311y** [comment]
Yes that makes sense. Thanks @adc17 .  No closer to passing this kata but issue closed.
