### ISSUE TITLE
Regex password verification help

### ISSUE THREAD

**Issue by FiddlersCode** [makersacademy/problem-solving#36]
hey all,

Working on this kata: https://www.codewars.com/kata/52e1476c8147a7547a000811/train/ruby

Having problems with my Regex.  Been reading all kinds of sites and poring over the Well-Grounded Rubyist and my brain is fried so I'm turning to you guys to help!  

From what I understand, the regex should do the following:
1. Check length being 6+ characters
2. Return to the beginning of the string and check that it contains at least on lowercase [a-z] character
3. Return to the beginning of the string and check that it contains at least one uppercase [A-Z] character
4. Return to the beginning of the string and check if there is at least one digit [0-9].

However, this code fails 5 out of my 7 tests (also below).

```
def check(password)
    regex = /\A(?=\w{6,})(?=[a-z]+)(?=[A-Z]+)(?=\d+)/
    if password =~ regex
    true
  else
    false
  end
end
```

```
require "regex"
describe "regex" do

  it "checks whether an expression contains at least one uppercase character" do
    expect(check("Cambridge4321")).to eq true
  end
  it "checks whether an expression contains at least one uppercase character" do
    expect(check("cAmbridge4321")).to eq true
  end

  it "checks whether an expression contains at least one uppercase character" do
    expect(check("cambridge4321")).to eq false
  end


  it "checks whether an expression contains at least one lowercase character" do
    expect(check("Cambridge4321")).to eq true
  end

  it "checks whether an expression contains at least one lowercase character" do
    expect(check("CAMBRIDGE321")).to eq false
  end

  it "checks whether an expression contains at least one digit" do
    expect(check("Cambridge4321")).to eq true
  end

  it "checks whether the password has at least six characters" do
    expect(check("Cambridge4321")).to eq true
  end
end
```

**Comment by TimRobinson1** [comment]
This specific kata will return true or false on its own if the regex finds (or doesn't find) the right things.  So you only need the first line "regex = /your-regex/".

Which tests are failing?
