### ISSUE TITLE
rspec test raise_error failure

### ISSUE THREAD

**Issue by FiddlersCode** [makersacademy/problem-solving#38]
![image](https://cloud.githubusercontent.com/assets/7489685/25073654/d4b82de8-22e2-11e7-8948-c6588eaff187.png)
Hi all,
Am tearing my hair out over this rspec issue.  I have the following tests (inside a ```Plane```) class:

```
  describe '#land' do
    plane = Plane.new
    it 'tests whether an instance of plane responds to land method' do
      expect(plane).to respond_to :land
    end

    it 'tests whether a landed plan has been added to the array' do
      plane.land(plane)
      expect($planes_landed). to include(plane)
    end

    it 'raises an error if a plane tries to land and the airport is full' do
      Plane::DEFAULT_CAPACITY.times { subject.land(Plane.new) }
      expect { subject.land(Plane.new) }.to raise_error 'Airport is full.'
    end
  end

The third test fails each time.  

The associated code is: 
 ```
  DEFAULT_CAPACITY = 10
  $planes_landed = []
  $planes_in_air = []

  def land(plane)
    fail 'Airport is full.' if $planes_landed.count >= DEFAULT_CAPACITY
    $planes_landed << plane
  end
```
The code has been thoroughly tested in IRB and works.  I expect the test to:
1. Create 10 new planes and add them to the ```$planes_landed``` array.
2. The airport will now be considered full.
3. I create an 11th ```Plane``` instance and try to land it.  It should fail because the airport is full.
4. The test should pass while raising the failure that the airport is full.

It looks like this runtime error does occor

**Comment by AlexChalk** [comment]
Hey @pmuldoon86 , what's `subject` set to here? That might have something to do with it.
Other than that I see two things:

1. Line 8: Looks like you're trying to land a plane on a plane.
2. Line 9: Gap between `.` and `to`.

Hope this helps!

**Comment by michaelbjacobson** [comment]
Hi @pmuldoon86, I might be totally wrong here but shouldn't your third test try to land planes `(DEFAULT_CAPACITY + 1).times`?

Mike

**Comment by AlexChalk** [comment]
One other thing to check—if you've landed a plane on subject in test one or two, I think that plane will stay landed for test three. Which would make test three error _before_ you've told it to expect an error.

i.e. If you land 1-2 planes in an airport, and then land airport.capacity planes in the airport, you'll get an error before you reach `expect { subject.land(Plane.new) }.to raise_error 'Airport is full.'`.

**Comment by FiddlersCode** [comment]
Hi all,
Thanks for comments - unfortunately they don't solve - 
1. Line 8 - this test is fine actually, just showed it for context
2. Line 9 - good spot, even rubocop didn't get it, but again this test is fine
3. Subject is set to a new instance of plane.  Have also tried it with `Plane.new.land(plane)` (I decided that the `land` method belonged to the plane and not to the airport)
4. @michaelbjacobson the test lands the default capacity of planes as a starting condition and then the next line adds one more plane, which should raise the error.   Your suggestion leads fo an uninitialized constant error.
5. Interesting point - I had landed a plane but in a previous separate block.  I tried commenting out that block but the error still occurs.  So still stumped :/

**Comment by AlexChalk** [comment]
> Line 8 - this test is fine actually, just showed it for context

So is this not the actual code? I would paste in what you've actually got, as the problem may occur on previous lines.

If Line 8 is your actual code, I think that's the issue. You land a plane on line 8, and it doesn't get removed from $planes_landed. You then try and land a bunch more planes, and you run into your capacity limit earlier than expected.
