### ISSUE TITLE
Use of grep to filter on multiple elements

### ISSUE THREAD

**Issue by Dino982** [makersacademy/problem-solving#39]
Hello, working on the CLM and stuck on step 6 

![clm step6 copy](https://cloud.githubusercontent.com/assets/19255596/25091730/aac1e092-239b-11e7-88cc-6489639629ca.jpeg)

![code input clm s6](https://cloud.githubusercontent.com/assets/19255596/25091955/ad651a84-239c-11e7-8589-b1c79e9670fe.jpeg)

**Comment by michaelbjacobson** [comment]
Hi Andrew, can you please let us know what command you're using and what you're wanting to achieve with it?

**Comment by KyeBracey** [comment]
Hi Andrew,

I got stuck on this too, until I realised I had completely misunderstood how piping works.  Check out "pipes and redirection" (lesson 18) again to make sure you've got that down.

grep only considers one line at a time (this is why we have to use the pipe operator, we can't do the whole thing with just one grep).  I suggest checking out how the -A, -B and -C switches change what grep does
(**$ man grep** to read the info on them).

Example: grep -A 3 "L337" vehicles

Then figure out how you can use the pipe operater to further narrow down your search with the other info.

Hopefully this helps you out without ruining the fun of solving it yourself :)

- Kye

**Comment by Dino982** [comment]
Hi Michael - command is at bottom of image - basically i am wanting to search through the vehicles file and filter out records that contain all the search criteria (i.e. Honda, Blue, etc)

**Comment by Dino982** [comment]
ok kye thanks for info. will give it a whirl!

**Comment by michaelbjacobson** [comment]
Hey Andrew, apologies - I only noticed the command at the bottom after I'd left that last comment. Have a look at the very helpful suggestions by Kye in the comment above this one. I would suggest running the command `$ man grep` and reading the manual there. The context flags will be very helpful for this!

**Comment by charlottebrf** [comment]
Hey @Dino982 bit late to the party, but this was also something I struggled with. Think @Kynosaur & @michaelbjacobson have given you some great responses so far. Chipping in here with a few thoughts...

Something that I found useful was to double check that each small step did what I assumed it did. That way when you then join together outputs of pipes you can be sure you get the result you expected. 

For example:
Check to see the output of: grep -A 3 "L337" vehicles 
Then check to see the output of: grep -B 2 "Blue" vehicles
Then assuming that matches your assumptions try piping them together & put them into a new file as you do so: grep -A 3 "L337" vehicles | grep -B 2 "Blue" > result.txt

Think of a filter search on Excel. Each grep will filter information. In this example, you are then 'piping' the result of that filter search to the next search. So the next grep flag will search the input given to it from the previous grep result. As the flags filter based on lines above (-A), below (-B), or above & below (-C) you need to think carefully about how you filter using grep flags. 

I wrote a blog post to try & deepen my understanding, in case this is helpful for you also you can read[ here](
https://medium.com/@charlottebrf/streams-in-the-command-line-ddcc7a967a13). Please excuse the ridiculous Katy Perry scenario...

Good luck!

**Comment by anitacanita** [comment]
@Dino982 Did you manage to find a solution for this?

**Comment by Dino982** [comment]
@anitacanita Spent a lot of time trying to figure it out but couldn't get the right sequence. Was taking up too much time so decided to crack on with the ruby. Will try and revisit and maybe have run through with pair partner or something

**Comment by Dino982** [comment]
ok managed to crack it with some sage advice from @si_ashbery!
