### ISSUE TITLE
How are people submitting pull requests to makersacademy/clmystery? 

### ISSUE THREAD

**Issue by AlexChalk** [makersacademy/problem-solving#4]
I've tried git request-pull 11c5ccfd270edaae027b0c976be9dfb7b30fa7a8 git@github.com:makersacademy/clmystery.git , but it's not showing up on github. Are people just using the github GUI?

**Comment by ns-winter** [comment]
Hi, yes I did it through the GitHub website, instructions on how are in the Detective's Handbook step6. 😊

**Comment by AlexChalk** [comment]
Thanks @ns-winter. Going to close this—it's not really a problem to use the browser, I just like knowing commands for everything :p.
