### ISSUE TITLE
Ruby Kickstart: Challenge 2:3 

### ISSUE THREAD

**Issue by charlottebrf** [makersacademy/problem-solving#42]
Hiya,

I'm having a bit of an issue with Ruby Kickstart Challenge 2, exercise 3_array.rb

My query is:
- See Screenshot below- I have included a (string) parameter to the every_other_char method 

- When I test this method and create the new instance of the string class & invoke every_other_char using my new instance using Josh's example string "abcdefg (see the commented out lines 23-24) as a new.rb file (not using the rake 2:3) the output in my command line gives me the expected output of every other char "aceg"

![3_array rb](https://cloud.githubusercontent.com/assets/16884984/25199299/4a74eb1e-2542-11e7-86f0-718932a9eb58.png)

However... when I run the rake 2: 3 test, I get a 'wrong number of arguments' error message of given 0, expected 1 (see  image below).

- I'm confused as to how the every_other_char method receives its string if I'm not manually adding a string parameter and then (as per lines 23-4) if I'm not creating the new instance & invoking the method. I know I'm not supposed to do this as that's why the rake tests are set up, and I know that it's taking in nil. 

![array_3 error msg](https://cloud.githubusercontent.com/assets/16884984/25199766/da1b7dea-2543-11e7-880b-596196c84956.png)

- If anyone can help to explain how the every_other_char receives the string and how rake tests that the output that would be much appreciated. I think the method itself is ok as it runs fine in my command line without the rake test.

**Comment by michaelbjacobson** [comment]
Hi Charlotte,

The problem here is that your `every_other_char`method requires an argument and, as you know, it's not being given one by the rake test. What the rake test will be doing is creating an instance of the string class, say `"abcdefg"`and then calling the method on this object using the dot notation, like this: `"abcdefg".every_other_char`. By doing this the method takes the string as input.

I hope this helps :)

Mike

**Comment by charlottebrf** [comment]
Thanks a lot @michaelbjacobson that's very helpful... I will go back to it & explore how I take out the parameter with the string. Much appreciated!

**Comment by charlottebrf** [comment]
So I've been mulling this over between challenges & at last I have cracked it! The key point of self & creating a new instance of the class at the same time as invoking the method, Thanks again @michaelbjacobson ! ![success](https://cloud.githubusercontent.com/assets/16884984/25248046/b4857100-2604-11e7-831c-9edbb25cd565.png)
