### ISSUE TITLE
Ruby Kickstart 2:3 method not returning array items with an even index.

### ISSUE THREAD

**Issue by SiAshbery** [makersacademy/problem-solving#43]
Hi guys,

I'm getting to grips with 2:3 and this is what I have so far:

class String
  def every_other_char
    letters = chars
    to_return = letters.select{|x|letters.index(x).even?}.join("")
    to_return
  end
end

Unfortunately, the select method I'm calling with a block that (I think) is asking for any entry with an even index, isn't bringing back even indexed items.

Instead it is bringing back seemingly random indexes so from "Four score and seven years ago..." I get indexes 0 2 4 6 10 12 14 16 19 20 26 28 30 31 32 which is ["F", "u", " ", "c", " ", "n", " ", "n", " ", " ", "g", ".", ".", "."] This is both the case in irb and when I rake. Any help would be massively appreciated.

**Comment by KyeBracey** [comment]
Hi Simon,

I did a little bit of messing around and it looks like when we call "letters.index(x)" that is returning the _first occurence_ of that character within the string (try running the below code to see what I mean):

`letters.each do |x|`
  `p "Checking #{x}"`
  `p letters.index(x) if letters.index(x).even?`
`end`

See if you can find another method to use before your block, to make finding the correct index easier. </cryptic hint>

**Comment by kkavita92** [comment]
Following up on what Kynosaur has already pointed out, I would look at one of these: 
https://ruby-doc.org/core-2.4.1/Enumerable.html#method-i-each_with_index
https://apidock.com/ruby/Enumerator/with_index

**Comment by KyeBracey** [comment]
^ Exactly what I was referring to, but less cryptic, haha.

**Comment by kkavita92** [comment]
Hahaha oops just saw your comment at the end. Sorry Simon for depriving you of a good hunt around ruby-doc.

**Comment by SiAshbery** [comment]
Nah all good, greatly appreciated guys, thanks :)
