### ISSUE TITLE
Kickstart 2:6 - looks right but fails.

### ISSUE THREAD

**Issue by dmcd84** [makersacademy/problem-solving#45]
So I have spend way too long on this one. I have googled extensively, tried multiple tweaks yet the code STILL fails. What am I missing? Some serious head banging is occurring!! 

![screen shot 2017-04-21 at 19 30 21](https://cloud.githubusercontent.com/assets/24233522/25291203/04bf6d50-26c9-11e7-8011-fd78a9ba1048.png)
![screen shot 2017-04-21 at 19 30 33](https://cloud.githubusercontent.com/assets/24233522/25291202/04b63a78-26c9-11e7-98cc-0fbb5682c3f7.png)

**Comment by dmcd84** [comment]
Updated the images - but still no further!!

**Comment by dmcd84** [comment]
Don't worry folks - a cup of tea and fresh eyes == solved! Moved the 'return true' out of the loop.

**Comment by lubosmichalic** [comment]
I'd change line 20  to `if (n < 2)`, 
just in case you called the method like this
`puts prime_chars?(['ab'])  # =>  false`, 
it'd return false, which is incorrect.
![screen shot 2017-04-21 at 19 58 50](https://cloud.githubusercontent.com/assets/26767476/25292194/062f758c-26cd-11e7-934e-0fdc0ecfc5c3.png)
