### ISSUE TITLE
Ruby Kickstart 3:4

### ISSUE THREAD

**Issue by charlottebrf** [makersacademy/problem-solving#46]
Another day another query...

I'm nearly there with Ruby Kickstart 3:4. One thing I need to resolve is to create a new array to use in my each_with_index loop which only contains the first occurrence of each to char. 

See my notes on the screenshot. As ever, any comments would be much appreciated!  ![ruby kickstart 3-4 query](https://cloud.githubusercontent.com/assets/16884984/25312575/ec6cef8c-2814-11e7-9384-22da70fe11d5.png)

**Comment by bannastre** [comment]
HINT: This where the '||=' incrementer comes in ;)

**Comment by charlottebrf** [comment]
Thanks @bannastre :)
