### ISSUE TITLE
Ruby Kickstart 3:2 

### ISSUE THREAD

**Issue by charlottebrf** [makersacademy/problem-solving#47]
Another query...

So the code for this I think is sound. One issue I have is because I shovel my evens_value into another array I create a multidimensional array, which translates through to my hash & so doesn't pass tests. 

I think I need a method on array that allows me to add all the elements from one array to another, or change how I push the result from line 21 to get my evens_value. 

Any advice much appreciated!

![ruby kickstart 3 2](https://cloud.githubusercontent.com/assets/16884984/25314720/1cee3b8a-2841-11e7-884e-bfe32659e7ef.png)

**Comment by bannastre** [comment]
Looks like you're setting your hash key to the full `odds_key` array and coming unstuck because you can't shovel into a Hash.
Each element of `odds_key` is to be a separate Hash key so something like ->
`odds_key.each { |e| Hash[e] = (1..e).to_a.select{ |num| num.even? } }`

**Comment by charlottebrf** [comment]
Thanks again @bannastre much appreciate you taking the time. Good luck with your challenges, hopefully I can help you at some point!
