### ISSUE TITLE
Student-directory Exercise 8 question 3

### ISSUE THREAD

**Issue by mralexsatur** [makersacademy/problem-solving#48]
Hi, I'm trying to return a sorted list of students whose name is only over 12 letters long. This is what I have so far.
I've added the method sort_students (line 29)

First of all I'm trying to push just the student names to a new array called unfiltered, then from there I want to push their names to a new array called answer (unimaginative names!) if their length is over 12. 

I changed the length to 2 in this example just so I can test it without typing out a load of long names!

when the below runs I get this and can't work out why its returning 6 blank lines but has something to do with the fact there were 6 entries. 

Any help would be greatly appreciated!

Owliver:exercises alexsatur$ ruby ex3.rb
Please enter the names of the students
To finish, just hit return twice
as
Now we have 1 students
asdf
Now we have 2 students
a
Now we have 3 students
w
Now we have 4 students
d
Now we have 5 students
as
Now we have 6 students

The students of Villains Academy
--------------
1. as (november cohort)
2. asdf (november cohort)
3. a (november cohort)
4. w (november cohort)
5. d (november cohort)
6. as (november cohort)
Overall we have 6 great students
Students names < 12 characters

Owliver:exercises alexsatur$ 

1. def print_header
2.   puts "The students of Villains Academy"
3.   puts "--------------"
4. end
5. 
6. def print(students)
7.   students.each_with_index do |student, index|
8.     puts "#{index + 1}. #{student[:name]} (#{student[:cohort]} cohort)"
9.   end
10. end
11. 
12. def print_footer(names)
13.   puts "Overall we have #{names.count} great students"
14. end
15. 
16. def input_students
17.   puts "Please enter the names of the students"
18.   puts "To finish, just hit return twice"
19.   students = []
20.   name = gets.chomp
21.   while !name.empty? do
22.     students << {name: name, cohort: :november}
23.     puts "Now we have #{students.count} students"
24.     name = gets.chomp
25.   end
26.   students
27. end
28. 
29. def sort_students(students)
30.   puts "Students names < 12 characters"
31.   unfiltered = []
32.   students.each do |student|
33.     unfiltered << student[:name]
34.   end
35.   unfiltered.each do |x|
36.     answer = []
37.     answer << if x.length > 2
38.     end
39.     puts answer
40. end
41. end
42. 
43. students = input_students
44. print_header
45. print(students)
46. print_footer(students)
47. sort_students(students)
48.

**Comment by charlottebrf** [comment]
Hey @alexanders89 I should be getting to this today, so once I've processed it with my own solution I will come back to this & see if I can give some informed opinions.

**Comment by mralexsatur** [comment]
Just sorted it :) 

seems so obvious!!

@charlottebrf thanks anyway :)

def sort_students(students)
  puts "Students names < 12 characters"
  unfiltered = []
  students.each do |student|
    unfiltered << student[:name]
  end
  unfiltered.each do |x|
    answer = []
    answer << x if x.length >= 2
    puts answer
    end

end

**Comment by AaronRodrigues** [comment]
Hey this is the way I did it. I didn't create any new arrays.

```ruby
def print(students)
k=1
  students.each_with_index do |student, i|
    next if student[:name].length > 12
    puts "#{k}. #{student[:name]} (#{student[:cohort]} cohort)"
    k+=1
  end
end
```
