### ISSUE TITLE
Step 5 help

### ISSUE THREAD

**Issue by j311y** [makersacademy/problem-solving#5]
On Step 5 you get this instruction after branching to `step-5`:
```
You found two witness interview files. Take a look inside both of them and save any useful information into a new file called 'interview_info.txt'.

You feel satisfied that you have covered your tracks - time to consolidate your files. Commit the file but DON'T PUSH IT YET!

First checkout back into the 'master' branch, and merge the 'step-5' branch into 'master'.`

```
I already saved the info it seems to be asking for in interviews.txt.
What information is meant to go in interview-info.txt?

**Comment by AlexChalk** [comment]
I think the interview numbers go in `interviews.txt`, and the interviews themselves go in `interview-info.txt`.

**Comment by j311y** [comment]
Thanks @adc17 seems I've skipped a step.
