### ISSUE TITLE
printing cohort for May issue

### ISSUE THREAD

**Issue by Simo72** [makersacademy/problem-solving#51]
Hi, been working on this for a way too long and for the life of me can't see it (sure it's staring me in the face)

getting the error "directory.rb:37:in `[]': no implicit conversion of Symbol into Integer (TypeError)"

line 37 is within the def by_cohort method.
any pointers from you lovely people?

Thanks

Ian

def input_students
  puts "Please enter the names of the students"
  puts "To finish, just hit return twice"
  # create an empty array
  students = []
  #get the first names
  name = gets.chomp.capitalize
  # while the name is not empty, repeat this code
  while !name.empty? do
    months = ["January", "February", "March",
              "April", "May", "June",
              "July", "August", "September",
              "October", "November", "December"
    ]
    puts "What cohort?"
    cohort = gets.chomp.capitalize
      if months.include? (cohort)
        puts "Favourite meal?"
        meal = gets.chomp.downcase
        # add the student hash to the array
        students << {name: name, cohort: cohort, food: meal}
        puts "Now we have #{students.count} students"
        #get another name from the user
        puts "New name?"
        name = gets.chomp.capitalize
      else
        puts "Cohort not found, please re_enter."
      end
  end
  # return the array of students
  students
end

def by_cohort(students)
  students.select do |name|
    if students[:cohort] == "May"
      puts "#{student[:name]} (#{student[:cohort]} cohort)"
    end
  end
end

# and print them
def print_header
  puts "The students of Villains Academy".center(75)
  puts "-------------".center(75)
end

def print(students)
  count = 1
  until count > students.count
    students.each_with_index.collect do |student, index|
      puts "#{index + 1}.#{student[:name]} (#{student[:cohort]} cohort) - loves to eat #{student[:food]}".center(75)
      count += 1
  end
end
end

def print_footer(names)
  puts "-------------".center(75)
  puts "Overall, we have #{names.count} great students".center(75)
end
# nothing happens until we call the methods
students = input_students

print_header
print(students)
print_footer(students)
by_cohort(students)
p students

**Comment by bannastre** [comment]
Here's your issue:
`if students[:cohort] == "May"`
students is an array, but the symbol is not within the array, it's within the hash within the array.
try: `students[index][:cohort]`
you'll need to define the index though...
Hope that helps!

**Comment by Simo72** [comment]
Thats a great help, thanks Bannastre
