### ISSUE TITLE
Student Directory 8:8 stuck!

### ISSUE THREAD

**Issue by charlottebrf** [makersacademy/problem-solving#52]
Hey all,

I'm stuck on the Student Directory 8:8 question which is:

> Once you complete the previous exercise, change the way the users are displayed: print them grouped by cohorts. To do this, you'll need to get a list of all existing cohorts (the map() method may be useful but it's not the only option), iterate over it and only print the students from that cohort.

See the below screenshot. I've created a method (with a hardcoded array of students) which currently can sort through each student and match its cohort to a given month, in this case :november. 

![screen shot 2017-04-28 at 09 48 53](https://cloud.githubusercontent.com/assets/16884984/25521586/1b48ee82-2bf8-11e7-8e90-eca3bf699cba.png)

I want it to check for a match against each of the students cohort month, find all matches and then shovel into a new array. Been struggling around with an each loop inside this one, but not making progress.

Any wisdom would be much appreciated!

**Comment by bannastre** [comment]
Hey, just to clarify, your output is currently returning all details for the students in the `:november` cohort?

So you're looking for a way to loop through each cohort rather than just `:november`?

Do you have an array of each of the other cohorts from an earlier exercise you could loop through on top of your `students.select` block?

**Comment by charlottebrf** [comment]
Hey @bannastre ..thanks again for answering!

> Hey, just to clarify, your output is currently returning all details for the students in the :november cohort?

Yes that's correct you can see the output in green on the right hand side of the screenshot

> So you're looking for a way to loop through each cohort rather than just :november?

Yes exactly, I think I need another with a counter in it to check each student cohort against all students cohorts & find the matches.

> Do you have an array of each of the other cohorts from an earlier exercise you could loop through on top of your students.select block?

I have this from an earlier exercise on cohorts: 

COHORTS_HASH = {"january" => :january, "february" => :february, "march" => :march, "april" => :april, "may" => :may, "june" => :june, "july" => :july, "august" => :august, "september" => :september, "october" => :october, "november" => :november, "december" => :december}

def gets_cohort()
  answer = asks_question("cohort").downcase
  if COHORTS_HASH.has_key?(answer)
    COHORTS_HASH[answer]
  else
    "none"
  end
end

**Comment by lubosmichalic** [comment]
Hi @charlottebrf , could I ask you to post your code so I could try and copy and paste it and have a play with it to try and find a possible answer?

**Comment by charlottebrf** [comment]
Heya @lnmichalic of course you can see my last commit [here](https://github.com/charlottebrf/student-directory/commit/8e75dfbbbe1c881b344f8c1ec0e52732f9d2e3f3) from exercise 8:7. Also uploaded as a md file here [directory.txt](https://github.com/makersacademy/problem-solving/files/963968/directory.txt) (in case that commit is difficult to play with/causes you work!)

This doesn't include the 8:8 work, as I was trying to get it working as a method & then add it as a separate method & amend the print method string interpolation so students appear sorted by index.

Please don't let me slow you down on your work though!

**Comment by lubosmichalic** [comment]
@charlottebrf no worries, I'm currently working on this at the moment as well, so good practice :)

**Comment by charlottebrf** [comment]
Okey dokey!

**Comment by lubosmichalic** [comment]
`students = [
  {:name => "The Joker", :cohort => :may},
  {:name => "Mr. Smith", :cohort => :may},
  {:name => "Dr.Hannibal", :cohort => :november},
  {:name => "Johnny", :cohort => :june},
  {:name => "Freddy Krueger", :cohort => :april},
  {:name => "Nurse Ratched", :cohort => :june},
  {:name => "Regina George", :cohort => :november},
  {:name => "Jean-Baptiste Emanuel Zorg", :cohort => :may},
  ]

def sorts_cohort(students)
  students.sort_by!{|student| student[:cohort]}
end

puts sorts_cohort(students)`

![screen shot 2017-04-28 at 10 48 21](https://cloud.githubusercontent.com/assets/26767476/25523890/4d8b0256-2c00-11e7-983d-e9833784a515.png)

As you can see, the months are not in order, merely alphabetical, but the students are grouped together.

I'm not sure if this is the output you're looking to get ? Hope this helps. If it's not let me know, and I'll try and work on it with you.

**Comment by bannastre** [comment]
so admittedly I've not tested this but maybe try something like:

`def sorts_cohorts(students, cohorts_hash)`
`sorted_by_month = [] `
`cohorts_hash.values.each do |cohort|`
`   sorted_by_month << cohort `
`   students.select { |student| sorted_by_month << student if student[:cohort] == cohort }`
`end`
`puts sorted_by_month`
`end`

I've not tested it so it might try and puts all the months then all the students but hope it gives an idea of how you might tackle :)

**Comment by charlottebrf** [comment]
Hey @lnmichalic & @bannastre that's super kind of you to take the time to help me with this.

I'm going to test out your suggestions, thank you so much! I'm hoping I can help you both with something at some point to return the favour.

Thanks again super kind. I feel re-energised to go back to this problem!

**Comment by lubosmichalic** [comment]
realized I might have missed a few things you wanted to do with your code (after looking at the exercise myself and rereading your initial question). So as an addon to the code I posted earlier, and very similar to what @bannastre posted 

def print_student_by_cohort(students)
  list_to_print =[]
  puts "Enter cohort to print:"
  user_input = gets.chomp
  students.map{|student| list_to_print << student if student[:cohort] == user_input.downcase.to_sym}
  list_to_print
end
puts print_student_by_cohort(students)

**Comment by charlottebrf** [comment]
Thanks so much @lnmichalic really appreciate it!

**Comment by cdscally** [comment]
I can't quite get this to where I am happy with it either, but maybe where I'm at will help you, or someone will pick up what I need to get it perfect.

So, given an array, 'students', containing hashes of the form {name: name, cohort: cohort}, I have been testing two separate outputs, which I'll just call 'Method 1' and 'Method 2'

Method 1 code - 

def print(students)
    &nbsp;&nbsp;puts students_by_cohort = students.group_by{|student| student[:cohort]}
end

Method 2 code - 

output = []
  &nbsp;&nbsp;students.each do |hsh|
    &nbsp;&nbsp;&nbsp;&nbsp;@months.each do |month|   #I had earlier created @months - an array of the month names
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if hsh[:cohort] == month
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;output << "#{month} cohort - #{hsh[:name]}"
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;end
    &nbsp;&nbsp;&nbsp;&nbsp;end
  &nbsp;&nbsp;end
  puts output.sort

And the outputs I get are
![image](https://cloud.githubusercontent.com/assets/6969146/25527622/77deb0a0-2c11-11e7-8b19-ba7121a372b9.png)

So in the Method 1 output, the months are ordered, and the hashes for each student are grouped by month. I think this technically meets our criteria but it looks so messy.

Method 2 has a much cleaner output but I can't figure out how to sort them by month!

Both should be easily extendible for hashes which contain ages, nationalities etc.

Hope that provides some help and interested to hear any critique.

**Comment by lubosmichalic** [comment]
@cdscally I was trying to figure out how to sort them by month in the correct order. 
 I had come across this and tried to implement it. 
http://stackoverflow.com/questions/6513855/sorting-an-hash-given-another-hash-including-information-about-the-order-method

But because I was sorting element student by student[:cohort] as opposed to just cohort, I couldnt quite get it to work. 

I'd say for now either Method you've got does a good job of making the ordered list. I think the only thing missing is the step where it only prints out a specific cohort. I'm sure that would tick all the boxes of that exercise. I've moved on to the next exercise although I've lost the previous functionalities and stylings, but will return to it later when all exercises are completed to clean up the code.

**Comment by cdscally** [comment]
I have a bad feeling that nesting these 'each blocks' is very bad practice, but if we use another one we can sort by iterating over the previously created array of month names.

So my 'Method 2' above becomes

output = []
  &nbsp;students.each do |hsh|
    &nbsp;&nbsp;@months.each do |month|
      &nbsp;&nbsp;&nbsp;if hsh[:cohort] == month
        &nbsp;&nbsp;&nbsp;&nbsp;output << "#{month} cohort - #{hsh[:name]}"
      &nbsp;&nbsp;&nbsp;end
    &nbsp;&nbsp;end
  &nbsp;end

  @months.each do |month|
    &nbsp;output.each do |str|
      &nbsp;&nbsp;if str.include? month.to_s
        &nbsp;&nbsp;&nbsp;puts str
      &nbsp;&nbsp;end
    &nbsp;end
  end

And the output is

![image](https://cloud.githubusercontent.com/assets/6969146/25528299/042747b8-2c15-11e7-9fe4-297708252a36.png)

**Comment by y0m0** [comment]
To sort them out you can either use the .[sort](https://ruby-doc.org/core-2.4.1/Array.html#method-i-sort) method and then use the <=> operator to define how to sort the elements, or more simply you can use the [.sort_by](https://ruby-doc.org/core-2.4.1/Array.html#method-i-sort_by-21) method and just pass it the :cohort value of each student hash.
Regarding the double each loop I would avoid it and go with the [Array.select  method](https://ruby-doc.org/core-2.4.1/Array.html#method-i-select)

**Comment by charlottebrf** [comment]
Thanks a lot @y0m0 that's also super helpful. Much appreciated!
