### ISSUE TITLE
step 14 question 1

### ISSUE THREAD

**Issue by jjadeseravla** [makersacademy/problem-solving#53]
hi, this question states that load_students() method and input_students() are almost the same and so extract them into one method.
However, I fail to see similarities between these 2 methods...is this instead referring to load_students method and save_students method?

Thanks in advance, 
Jade

**Comment by KyeBracey** [comment]
Hi Jade,

I think it's just talking about the part where we append the @students array, rather than the methods as a whole.

I don't think it's talking about save_students and load_students, because we have to explicitly open the file to read or to write for each one.

~Kye
