### ISSUE TITLE
Fizzbuzz alternate solutions

### ISSUE THREAD

**Issue by tobywinter** [makersacademy/problem-solving#54]
When trying to solve for this alternate test the method is coming back as undefined when running rspec in irb. 

it 'returns "fizz" for the number 3' do
  expect(3.fizzbuzz).to eq 'fizz'
end

Writing fizzbuzz as a method in an integer class doesn't seem to work, how can I write a method that the test will pass on 3? 

![pasted image at 2017_05_02 03_07 pm](https://cloud.githubusercontent.com/assets/26612122/25621404/2b811140-2f49-11e7-9821-73182cf890d8.png)

**Comment by nikeshashar** [comment]
Quick Tip: Try to avoid leaving `puts` inside of methods.

**Comment by tobywinter** [comment]
The problem we're having is getting the method to pass on '3'. Our solutions keep returning these issues: 
![pasted image at 2017_05_02 03_18 pm](https://cloud.githubusercontent.com/assets/26612122/25622191/8924b084-2f4b-11e7-9436-444854652be2.png)

**Comment by charlottebrf** [comment]
Hey @tobywinter I am getting to this tomorrow with my pair so can reply in my depth once we have got there.

As some general interim advice which I hope helps you:

- Have you gone through each error message to systematically problem solve what the issue could be with your pair? 

- Have you checked that the assumptions you've made about what the code does are correct? (Puts can be helpful for this, to display code at different points in your code & confirm it matches what you think it should be.)

- Did you see [this post](https://blog.makersacademy.com/how-i-solve-problems-a6a84d167598)? I found it quite a useful guide on practical steps you can take to unpick big problems into smaller ones.

I'll be back in touch tomorrow!

**Comment by nikeshashar** [comment]
@tobywinter is your code on Github anywhere?

**Comment by tobywinter** [comment]
Thanks guys, we've realised we'd missed the quote marks around our method in the test, so our test was the problem not our code!! So.. problem solved?
