### ISSUE TITLE
Step 9 - just checking

### ISSUE THREAD

**Issue by saralynnazuk** [makersacademy/problem-solving#6]
I caught the baddie!!! Before I do the final commit and push though, I just wanted to check a couple things:
1) The instructions say to not add any **extra** spaces in jail.txt but this still means I should put a space between the convict's first and last name (just no additional spaces at the beginning/end, etc.), right? 
2) When I checked the permissions on my jail.txt file it showed -rw-r--r-- which, from my understanding, means that only the user (me) has permission to write and group/others have only read permission. This is what I want and thus no need to change anything, right?

**Comment by JayWebDevCom** [comment]
Hi, yes I think you are good to go - on both counts. I think that if you do it correctly, there should be a green tick next to your pull request on the makers-clmystery github page. Whereas right now there should be a red cross...

**Comment by saralynnazuk** [comment]
Great, thanks for your help @JayWebDevCom!
