### ISSUE TITLE
Step 6 of clmystery is a mystery to me 

### ISSUE THREAD

**Issue by annalaise** [makersacademy/problem-solving#60]
Hello everyone. I'm trying to write the correct command for multiple keyword filtering of the vehicles file, using grep, flags and pipes. I can get the first grep to save a list of matched licence plates (and the subsequent 6 lines) to the suspects.txt file using this:

`grep -A 6 "L337" vehicles > suspects.txt`

However, when I add pipes and start trying to filter this further for Honda, Blue, or 6', the terminal either just shows `>` on the next line and I can't escape it, or it simply overwrites the suspects.txt file with the results of the last string in the pipeline (e.g. Make: Honda \n, over and over again) 

To reproduce the above, this is what I entered: 

`grep -A 6 "L337" vehicles | grep "Honda" > suspects.txt`

I have searched the interwebs and can't find anything that helps me to understand how to search for multiple words in a file, and gather them together as a collection of matches to  output to a file. Any help appreciated!

**Comment by i-hardy** [comment]
I ran into the same issue with the mysterious `>`- if you're only getting it after searching for 6', I think it's because the terminal sees the `'` as the start of a new string and wants you to enter the rest of it.

As for the other issue, you need to keep the `-A, -B, -C` operators for each search, or else it'll just narrow it down to the line that has the word you've passed to grep.

**Comment by aballal** [comment]
At each stage of filtering you shouldn't be losing the lines before and/or after it. At the first stage you filtered on L337 and correctly picked up 6 lines after it. At second stage filter on Honda but save info before and after it using -A and -B. And so on. So at each stage you should have all 6 lines for each vehicle.

**Comment by annalaise** [comment]
Awesome, thanks all for your help :D
