### ISSUE TITLE
Automatic tests failing when submitting pull request 

### ISSUE THREAD

**Issue by annalaise** [makersacademy/problem-solving#62]
Hi all (again) 

I've created a new pull request at Step7 of the weekly challenge, and am getting this error message: 

![image](https://user-images.githubusercontent.com/17883880/27000299-04342008-4de1-11e7-9aa3-401f20f5b484.png)

It looks like an automatic test is failing, but I've followed the steps exactly. Any ideas?

**Comment by SaphMB** [comment]
I don't think this test passes until the challenge is complete. Mine initially failed but passed at the end.
