### ISSUE TITLE
Ruby KickStart: 2:9 - Hey Grandma!

### ISSUE THREAD

**Issue by langphil** [makersacademy/problem-solving#64]
I cannot for the life of me work out why the code I've written for this challenge is failing. It works as described when I run it in terminal, but it fails when I rake. 
```
def deaf_grandma
  while true
    answer = gets.chomp
    if answer != answer.upcase
      puts 'HUH?! SPEAK UP, SONNY'
    elsif answer == "BYE"
      break
    else
      puts 'NO, NOT SINCE 1938!'
    end
  end
end
```

**Comment by EOSullivanBerlin** [comment]
Maybe you need to return rather than puts?

**Comment by aballal** [comment]
You have a missing ! after SONNY. Add it and see if it works.

**Comment by langphil** [comment]
Ah, yes, so simple! Thank you @aballal
