### ISSUE TITLE
Step 5 in clmystery 

### ISSUE THREAD

**Issue by EOSullivanBerlin** [makersacademy/problem-solving#65]
I don't know what is being asked in step 5.
I have looked for other branches with "git branch -a" and there is no STEP_5 branch. 
I used "git log"  and moved to older commits with "git checkout". Obviously, I was always in the master branch and the earlier the commits still pointed to a STEP_5 branch that I could not find. 

I move on because it was taking too long and found the rest of the steps straightforward. Although at a later I was asked to submit a pull request but because I was on the master branch this was not possible/ make sense.

I was able to create my own branches "git checkout -b [name_of_your_new_branch]" and pull requested.

Can you see where I am going wrong?

**Comment by nikeshashar** [comment]
@EOSullivanBerlin It would be useful if you could add a link to your current work. Try forking the original repo and do stages 1 - 5 again to see if it makes a difference?

**Comment by EOSullivanBerlin** [comment]
Okay I will.

**Comment by EOSullivanBerlin** [comment]
I set it up incorrectly. I forked it up you could say. I still have an issue with step5. My branches look like this.
![image](https://user-images.githubusercontent.com/27338309/27066075-d2ebdbf8-5001-11e7-97a3-2ad2ac989901.png

**Comment by EOSullivanBerlin** [comment]
I did set it up incorrectly. You could say I forked it up. However, I am still a scratching my head as to what to do with step5 and branching. These are the branches available to me. 
![gitbranch-a](https://user-images.githubusercontent.com/27338309/27066122-1d54e266-5002-11e7-956a-3a9906a6d574.jpg)

**Comment by Tambi-Mat** [comment]
Hi Eoin, You want to use the remotes/origin/step-5 branch I think

**Comment by aballal** [comment]
@nikeshashar - There is no step-5 branch in https://github.com/makersacademy/clmystery itself. I have looked through few of our clmystery and they all have 5 branches which implies we must have got them when we forked from makersacademy. However, currently both makersacademy/clymsytery and hence https://github.com/EOSullivanBerlin/clmystery don't have the step-5 branch. Seems like something has changed between us forking and EOSullivanBerlin forking but I can't see it in the commit logs. Am I completely off base here?

**Comment by Tambi-Mat** [comment]
Can Eoin fork from our already forked repos with the 5 branches and step-5??

**Comment by Tambi-Mat** [comment]
i.e the repos we forked onto our profiles

**Comment by aballal** [comment]
I was thinking EOSullivanBerlin could fork from one of us and then rollback to the point before our first commit i.e Dec 12, 2016 one. But it is probably better if Nikesh has a look and fixes the root cause if it is in makersacademy repo. So didn't mention it.

**Comment by nikeshashar** [comment]
Nothings changed on the Makers Repo from what I can see folks.

**Comment by aballal** [comment]
@nikeshashar - Why doesn't makersacademy/clmystery currently not have step-5 branch?

**Comment by nikeshashar** [comment]
@aballal - The repository version we have is blank slate. What would lead you to believe we need a branch called `step-5` ?

**Comment by aballal** [comment]
Because step-5 branch already existed in our remote repo. We merely checked out that branch worked on it and checked out the master back. How did it get there if it didn't come when we forked it?

**Comment by tobold** [comment]
I'm a bit confused by this. When I did the challenge I had to use `git checkout` to switch from the `master` branch to the `step-5` branch and then `git pull` in order to get the new version of step5.md.

Now looking at the makersacademy/clmystery repo there is no `step-5` branch available. 

@nikeshashar in step5.md it says;
> To recover your 'step5' file, use the `git checkout` command to check out the 'step-5' branch, and try to view this file again.

**Comment by nikeshashar** [comment]
> Because step-5 branch already existed in our remote repo. 

When you fork a repository from another, it won't automatically create branches for you. Is there anything before then that you did to create the new branch yourself?

**Comment by aballal** [comment]
No, I didn't create that branch. And I didn't write the updated instructions there were in step5 file when I switched to step-5 branch. I only followed instructions mentioned in all step files. Nothing else. So I don't understand how step-5 branch is in most of our repos but not currently in makersacademy repo.

**Comment by tobold** [comment]
When we cloned the repo (git@github.com:makersacademy/clmystery.git) we received 5 branches, shown here:
![branches 1](https://user-images.githubusercontent.com/23635603/27078388-742a109c-502b-11e7-813c-ec58bf7f8a38.PNG)

Currently, the clmystery repo has 2 branches (shown below), neither of which are called `step-5` and so step 5 of the challenge cannot be completed.
![branches 2](https://user-images.githubusercontent.com/23635603/27078392-768c6524-502b-11e7-89d6-75dc21156dd2.PNG)

**Comment by nikeshashar** [comment]
Okay - we're investigating now. Sorry!

**Comment by nikeshashar** [comment]
Github blames me! Sorry folks. It should be back now : 

![image](https://user-images.githubusercontent.com/7963753/27080552-4d485f84-5034-11e7-8da2-1f69aa2c46df.png)

**Comment by EOSullivanBerlin** [comment]
Now it works. Thanks, I was away working all day and it was really pleasant to have an answer for it when I was finished.  Much appreciated. I learnt my lesson ask questions quickly and often.
