### ISSUE TITLE
Ruby Kickstart Tut: The logic behind session 1 question 4 

### ISSUE THREAD

**Issue by Tambi-Mat** [makersacademy/problem-solving#66]
Hello good people.

I am trying to understand the logic behind the solution for the Ruby Kickstart tut, session 1 question 4. The "why?" of the solution is what I'm struggling with. And I suspect there is a much better and elegant solution? 
Any help in understanding the logic will be welcome.
Cheeers

**Comment by ckiteou** [comment]
Hi @Tambi-Mat, Ruby will execute the code within the 'if' statement providing the argument passed to the parameter 'reads_books' is 'true. If the argument passed is 'false', Ruby skips the 'if' statement and will execute the code within the 'else' statement. Respectively, the code within either 'if'/'else' will execute providing that the argument passed to the parameter 'num_books' meets one of the respective conditions, which in turn, will return the respective 'grade' value. Maybe others have been able to refactor the code to make it more Ruby (simple/prettier...)? I hope this helps :)

**Comment by Tambi-Mat** [comment]
Hi Costas. Thank you!!
