### ISSUE TITLE
Ruby-Kickstart and the rake test.

### ISSUE THREAD

**Issue by EOSullivanBerlin** [makersacademy/problem-solving#67]
I have picked Ruby-Kickstart as my Tutorial to complete this week and I am using cloud nine IDE. 
I have been work my way through the challenges but I don't know how to use the rake tests that he uses in his videos to check my answers. So far I have just been creating new ruby files and writing the code so that it puts the answer to output. I then check it to see if its what I expected. Works fine but its a bit of a pity. 

Did anyone get this working? What do I have to do to run the tests in my text editor on cloud nine.

**Comment by funmia** [comment]
Hey I had the same issue with the tests. Try running  gem install rspec  from the same directory as your Rakefile, then see you you can run any test from the challenges  e.g rake 1:1 
that solved it for me. I think it's because you don't have that gem installed already

**Comment by EOSullivanBerlin** [comment]
I will give that a go now thanks.

**Comment by EOSullivanBerlin** [comment]
I ran "gem install rspec" in the same directory as the Rakefile.  That seem to install a number of gems successfully. However, when I run "rake 1.3" followed by the file name that I want to test in my terminal it returns an error because it claims that the file is returning the wrong output. It's not.
I am probably just making a basic error. Any ideas.

**Comment by EOSullivanBerlin** [comment]
Never mind its working great now. Thanks for your help again.

**Comment by funmia** [comment]
Maybe a syntax error,  you're using  "." Instead of ":" for the test; rake 1:3 
See if that works or post a screenshot of the error message you get.

**Comment by funmia** [comment]
Great 🙂
