### ISSUE TITLE
Ruby Kickstart Gem::MissingSpecVersionError

### ISSUE THREAD

**Issue by Nandhini31** [makersacademy/problem-solving#69]
I cloned rubykickstart from makers page. I installed gem install rspec and gem install bundler . It installed rspec 3.6.0 . When I try running rake 1:1 I get

in /Users/Nandhini/Projects/ruby-kickstart)
rake aborted!
Gem::MissingSpecVersionError: Could not find 'rspec' (~> 3.2.0) - did find: [rspec-3.6.0]
Checked in 'GEM_PATH=/Users/Nandhini/.rvm/gems/ruby-2.4.0:/Users/Nandhini/.rvm/gems/ruby-2.4.0@global', execute `gem env` for more information
/Users/Nandhini/Projects/ruby-kickstart/Rakefile:1:in `<top (required)>'
/Users/Nandhini/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by ghost** [comment]
Try and run the rake 1:1 when in the folder
```
 /Users/Nandhini/Projects/ruby-kickstart/session1/challenge/
````
same folder where you have your file "1_arithmetic.rb"

**Comment by Nandhini31** [comment]
Nandhinis-Air:3-challenge Nandhini$ ls
1_arithmetic.rb		3_simple_logic.rb	5_string.rb		7_string.rb
2_arithmetic.rb		4_logic.rb		6_string.rb
Nandhinis-Air:3-challenge Nandhini$ rake 1:1
(in /Users/Nandhini/Projects/ruby-kickstart)
rake aborted!
Gem::MissingSpecVersionError: Could not find 'rspec' (~> 3.2.0) - did find: [rspec-3.6.0]
Checked in 'GEM_PATH=/Users/Nandhini/.rvm/gems/ruby-2.4.0:/Users/Nandhini/.rvm/gems/ruby-2.4.0@global', execute `gem env` for more information
/Users/Nandhini/Projects/ruby-kickstart/Rakefile:1:in `<top (required)>'
/Users/Nandhini/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
Nandhinis-Air:3-challenge Nandhini$

**Comment by Nandhini31** [comment]
OK I solved it using this https://stackoverflow.com/questions/25107583/rake-aborted-gemloaderror-could-not-find-rspec-x-but-did-find-y

gem uninstall rpsec 
gem install rspec -v 3.2.0
