### ISSUE TITLE
Step 6  -  Pull request failed clmystery

### ISSUE THREAD

**Issue by JessicaBarclay** [makersacademy/problem-solving#7]
So I am following these instructions found in the detective_handbook for Step 6

"You forked a repo, cloned it to your computer, made some changes committed and pushed them back to Github. Now if you want to submit those changes back to the original repo you would need to make a Pull Request. The maintainers of the original repo can review your changes and decide if they want to merge them. Refer to the [Github guide](https://help.github.com/articles/creating-a-pull-request/) to learn how to make a pull request."

**I followed the instructions from the article above - but after submitting the Pull request it said it had failed (See pics)
Should I be doing a pull request from the command line? Or am I being stupid! I feel like I might not be doing the right thing... I followed the guide but now I'm stuck :(**

![screen shot 2017-03-16 at 23 27 56](https://cloud.githubusercontent.com/assets/20893719/24022852/bb16c7f0-0aa0-11e7-968a-ee2a43485173.png)
![screen shot 2017-03-16 at 23 23 52](https://cloud.githubusercontent.com/assets/20893719/24022853/bb1a1860-0aa0-11e7-8f7b-29b5bd1df178.png)

**Comment by JayWebDevCom** [comment]
Click the blue details link by where it says "The Travis CI build failed".

Does it say something about a jail.txt file? If so, don't worry. Carry on with the steps and instructions until you produce a jail.txt file and commit and push.

That should rectify the error. Let me know how it goes.

**Comment by TimRobinson1** [comment]
As Jay said, it's probably to do with the jail.txt file.  I'm pretty sure it's checking for whether or not you've got the right name down as the criminal, so it won't give you a green tick until you finish the mystery and create the jail.txt file during the final step. 😄 

So don't worry about it for now, I'm fairly sure once you're finished it'll be resolved.

Hope it works out!  Terminal City is counting on you - they're slippery buggers, those criminals. 😛

**Comment by JessicaBarclay** [comment]
@JayWebDevCom 
Yes that sounds about right! I have attached the error you described, I will carry on hunting for now - thank you!

![screen shot 2017-03-16 at 23 57 44](https://cloud.githubusercontent.com/assets/20893719/24023471/74485d8a-0aa4-11e7-8c4c-6e7cb2fbf6cb.png)

**Comment by anitacanita** [comment]
@JessicaBarclay Don't forget to close the issue if it's sorted out 😃

**Comment by JessicaBarclay** [comment]
All sorted now, thanks guys!
