### ISSUE TITLE
Ruby kickstart session 2, challenge 2

### ISSUE THREAD

**Issue by kitkat119** [makersacademy/problem-solving#70]
Can anyone help me work out why my code isn't passing? 
The challenge: # Prompt the user for a number, then read it in and print out "hi" that many times
 Repeat this process until the user submits "bye", then say "goodbye" and end the program
 HINT: Check out example 2 if you get stuck

My code:

def hi_hi_goodbye
  print "Please enter a number between 1 and 10"
  while number = gets
    number.to_i.times { print "hi " } 
    break if number.chomp == "bye"
  end
  puts "goodbye"
end

Failure message:
Failures:

  1) hi_hi_goodbye says "hi" 6 times and "goodbye" once when given "4,2,bye"
     Failure/Error: expect(output.scan(/\bhi\b/mi).length).to eq self.class.sum(inputs)
       
       expected: 6
            got: 5
       
       (compared using ==)
      ./session2/spec/2.rb:33:in `hi_hi_goodbye_tester'
      ./session2/spec/2.rb:42:in `block (2 levels) in <top (required)>'

Finished in 0.00167 seconds (files took 0.09403 seconds to load)
2 examples, 1 failure

**Comment by Tambi-Mat** [comment]
Hi. Have you tried another "end" at the end of the def block?

**Comment by Tambi-Mat** [comment]
sorry Kat. Please ignore my comment.

**Comment by artemisxen** [comment]
Instead of print "Please enter a number between 1 and 10" try with puts.

**Comment by ghost** [comment]
@kitkat119 try this:
on: print "Please enter a number between 1 and 10 ", add a space before closing the string, right after 10. 
or print it out with puts as @artemisxen suggested.

```
def hi_hi_goodbye
	print "Please enter a number between 1 and 10 "
	while number = gets
		number.to_i.times { print "hi " }
		break if number.chomp == "bye"
	end
	puts "goodbye"
end
```

**Comment by aballal** [comment]
@kitkat119 - It would be better if you check for the break condition before attempting to print. The rake will pass with the change suggested by @artemisxen and @AlexSusanu above, this change isn't needed.

**Comment by oleglukyanov** [comment]
I'd say `puts` not `print`.
Also you want to check for 'bye' before converting input into integer.
Like this:

```
def hi_hi_goodbye
  puts 'Please enter a number between 1 and 10'
  while input = gets.chomp 
    break if input.downcase == 'bye'
    input.to_i.times {puts 'hi '} 
  end
  puts 'goodbye'
end
```

**Comment by kitkat119** [comment]
thank you!
