### ISSUE TITLE
Ruby Kickstart Session3 challenge 2

### ISSUE THREAD

**Issue by adoolaeghe** [makersacademy/problem-solving#71]
I've been looking for a while now how to fix this error. If anyone has an idea where the error comes from? 

Is it because I'm including an array in my `to_return` Hash key ? 

```
def staircase(n)
    to_return = Hash.new(0)
    arr = []
  for i in 1..n do
    arr << i if i.odd?
  end
  result = []
  arr.each do
    |e| for b in 0..e do
    result << b if b.even?
    end
  end
to_return[arr] = result
end
```
The rake returns error 1 failure on 2 Exemple 
```
 1) staircase staircase(1) # => {1=>[]}
     Failure/Error: expect(staircase n).to eq result

       expected: {1=>[]}
            got: [0]

       (compared using ==)
     # ./session3/spec/2.rb:15:in `block (3 levels) in <top (required)>'

Finished in 0.01887 seconds (files took 0.07608 seconds to load)
2 examples, 1 failure
```

**Comment by aballal** [comment]
Array index start from 0. Hence for loop should run from 0...n. Notice the triple dots.
Edited: Sorry, I don't know why I had arr[i] in my head! Please ignore the above.

**Comment by aballal** [comment]
I think you will run into more problems as well. It's better to add straight away into hash than put it an array and then try to make a Hash out of it. Haven't tried your code out.
Suggested Steps:
1. Create an empty hash
2. First loop: For each odd number up to n add it as the key and value []
3. Second loop: For each even number, select the keys that are greater than that number, and shovel the number to its value array.
4. return the hash
Note: In the above algorithm the two loops are separate and not nested.

Edited: Here's the code for above:
```
def staircase(n)
  odd_even = Hash.new
  1.upto(n) { |i| odd_even[i] = [] if i.odd? }
  1.upto(n) { |i| odd_even.select {|key,value| key > i}.each {|key,value| value << i} if i.even? }
  odd_even
end

```

**Comment by ghost** [comment]
@adoolaeghe try this:

```
def staircase(n)
    to_return = Hash.new(0)  #=> your hash

    arr = [] #=> your empty array for odd numbers
	  for i in 1..n do
		arr << i if i.odd? #=> for each number upto n, add all odds to array
	  end
	arr.each {|i| to_return[i]=[]} #=> now from this array, take all numbers and add them as key to the hash with value [] (Array.new) 

	
    result = [] #=> your empty array for even numbers
	arr.each do |e| #=> loop through your odd numbers array
		for b in 1..e do #=> for each number upto your e, check which one is even
    		to_return[e] << b if b.even? #=> if that number is even, add it as value to your hash[e] = [b], repeat
    	end
	end

	to_return #=> return your hash
end
```

**Comment by aballal** [comment]
Doing it with your way of for loops but without the arrays. 

```
def staircase(n)
  to_return = Hash.new
  for i in 1..n do
    to_return[i] = [] if i.odd?
  end
  to_return.each do |key,value|
    for i in 2...key do
      to_return[key] << i if i.even?
    end
  end
  to_return
end
```

**Comment by ghost** [comment]
Nice

**Comment by adoolaeghe** [comment]
Great, It passed after adding directly the odds to the hash as you suggested. thanks @aballal  @AlexSusanu .
