### ISSUE TITLE
Ruby Kickstart Session 2  Challenge 11

### ISSUE THREAD

**Issue by Nandhini31** [makersacademy/problem-solving#73]
Hi,

Can someone explain  this 👍 
 %w(zero ten twenty thirty forty fifty sixty seventy eighty ninety)[n/10]
 what %w()[n] means? 

Thanks!

**Comment by ghost** [comment]
%w(zero ten twenty thirty forty fifty sixty seventy eighty ninety) #=> is a shortcut to do
```
["zero", "ten", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"] 
```
[n] #=> get the n-th position from this array

```
%w(zero ten twenty thirty forty fifty sixty seventy eighty ninety)[9]
"ninety"
```
[n/10] #=> get the position thats the result from n divided 10
n = 54
[100/10] #=> position 5 ("fifty")


at least thats how I understand it...

**Comment by EOSullivanBerlin** [comment]
You can make an array quickly with %w(list of all the things you want in an array) this saves you having to format it yourself.

You can select an element from an array based on its position using [n].

I hope that helps.

**Comment by Nandhini31** [comment]
Thanks @AlexSusanu  and @EOSullivanBerlin
