### ISSUE TITLE
kickstart 2:6

### ISSUE THREAD

**Issue by kitkat119** [makersacademy/problem-solving#74]
Can't work out why this isn't passing and it's driving me up the wall.....thank you

Write a method named prime_chars? which takes array of strings
 and returns true if the sum of the characters is prime. 

def prime_chars?(strings)
    sum = strings.join.length 
    for i in 2...sum
        return false if sum % i == 0
    end
    true
end 

Failures:

  1) prime_chars? should not be
     Failure/Error: specify { expect(prime_chars? []).to_not be }
       expected true to evaluate to false
     ./session2/spec/6.rb:3:in `block (2 levels) in <top (required)>'

**Comment by ghost** [comment]
@kitkat119 

My math is my weak point so I googled a bit (a bit more) ..
I don’t remember where I read it (somewhere on stack over flow) that to find a prime number you need to divide up to the square root of that number (if I understood correctly)

```
def prime_chars?(strings)
	sum = strings.join.length
	return false if sum <= 1  #=> add this so that sum is always positive, otherwise the rake test will 
                                                 throw an error (don't remember exact error)

	for i in 2..Math.sqrt(sum) #=> here you square your number
		return false if sum % i == 0
	end
end
```
You can have a look here:
https://math.stackexchange.com/questions/5277/determine-whether-a-number-is-prime

**Comment by kitkat119** [comment]
Thank you for helping, it passed after adding the return false if sum <= 1, hurray!
