### ISSUE TITLE
Questions on Session 2 Challenge 12

### ISSUE THREAD

**Issue by Nandhini31** [makersacademy/problem-solving#75]
1. Include setter methods called numerator and denominator that allow the user to change these values --> Does he mean explicitly set a setter method and getter method or  use attr_accessor?
2.Why do we not pass in variables for these methods ? def to_s and def to_f  as in 
def to_s(numerator,denominator) 

end

def to_f(numerator,denominator) 

end

**Comment by paulmillen** [comment]
The way I've interpreted "Include setter methods called numerator and denominator that allow the user to change these values" is to use attr_accessor and the initialize method for the two variables.

You don't need to pass arguments to the class methods in this case.  The method will be used on instances of the Fraction class which are instantiated with the two variables used in the methods.  When f.to_s or whatever is called, to_s can access the variables that f possesses.
