### ISSUE TITLE
Clarification: Week 3, Step 8

### ISSUE THREAD

**Issue by langphil** [makersacademy/problem-solving#77]
In Week 3, Step 8 I'm asked:

"Rewrite the each() method that prints all students using while or until control flow methods (Loops)."

Does this mean that I should replace the 'each()' method entirely, or factor in a While loop within it?

**Comment by BDCraven** [comment]
Hi Phil

I interpreted it to mean the former - replace the each() method with either a while or until loop (so replicate the same effect but using a while/until loop), but I could be wrong...

**Comment by meta-morpho-sys** [comment]
HI all,
I am trying to write a while loop for step 4(section 8) "Rewrite the each() method that prints all students using while or until control flow methods (Loops)."

I can't figure out how to make my while loop iterate over the array of hashes.  So far my code only got me through to printing out the hashes:
{:name=>"Thomas", :cohort=>:november}
{:name=>"Alex", :cohort=>:november}
{:name=>"Sonya", :cohort=>:november}

How do I get to use the key :name?

This is my code
arr = [{name: 'Thomas', cohort: :november}, {name: 'Alex', cohort: :november}, {name:'Sonya', cohort: :november}]
index =0
while index < arr.length
  puts arr[index]
  index += 1
end

Thank you :-)

**Comment by SaphMB** [comment]
You're nearly there, you just need to add the key for what you're trying to access, in this case name,  within the puts statement

arr = [{name: 'Thomas', cohort: :november}, {name: 'Alex', cohort: :november}, {name:'Sonya', cohort: :november}]
index =0
while index < arr.length
puts arr[index]**[:name]**
index += 1
end

**Comment by meta-morpho-sys** [comment]
Thanks a lot, Saph!

**Comment by SaphMB** [comment]
You're welcome ☺️
