### ISSUE TITLE
Sum without highest and lowest number

### ISSUE THREAD

**Issue by congcongbo** [makersacademy/problem-solving#78]
Can anyone explain what the error means please, and how to solve it? Thanks!

Challenge:
Sum all the numbers of the array (in F# and Haskell you get a list) except the highest and the lowest element (the value, not the index!).

My code:
```
def sum_array(arr)
  #your code here
  if arr.length > 2
    arr.sort!
    arr.delete_at 0
    arr.delete_at -1
    sum = 0
    arr.each { |x| sum +=x }
    return sum
  else
    return 0
  end
end
```

Error:
on nil or empty
```
#
 `sum_array'
 `block (2 levels) in 
'
```

**Comment by paulmillen** [comment]
Hi, your code doesn't account for a condition where the array passed to it is nil or empty.  (Specifically nil, from what I can tell as your code works with [] or [nil].)

**Comment by congcongbo** [comment]
Thanks Paul. How do you write this condition? I tried

`arr.class == NilClass`

for nil and

`arr.length == 0`

but still got the error

**Comment by paulmillen** [comment]
you could just use if arr && arr.length > 2.  It will check if arr is true - ie not false or nil.  
Or also arr.is_a?(Array).

**Comment by congcongbo** [comment]
Thanks, it worked!
