### ISSUE TITLE
Challenge step 5

### ISSUE THREAD

**Issue by will-gant** [makersacademy/problem-solving#8]
Heya

I feel I must be making some kind of very daft mistake here, but I'm stuck on step 5. The instructions seem simple enough - I've switched to the step-5 branch and re-opened the file. The problem is that the file's contents are exactly the same as before, and not the different version that I know is supposed to appear. The thing I can't understand is that the correct contents _do_ appear when I navigate to (apparently) the exact same file on the step-5 branch using the Github GUI...

![screenshot 2017-03-17 at 10 16 57](https://cloud.githubusercontent.com/assets/20523607/24036769/68ec3e6e-0afb-11e7-9ec6-5ce6d593edad.png)

**Comment by ns-winter** [comment]
Hey, looks weird, only thing I can think of is try checking out the step5 instructions in the mystery folder (rather than the detective's handbook).

**Comment by will-gant** [comment]
Yep, that was in the clmystery folder (higher up in the screenshot, I was looking in the detective_handbook folder, but I returned to clmystery to open step5)

**Comment by ffasolin** [comment]
Hey, that is weird. Have you merged your master into that one? Seems like it might have been overwritten locally.

**Comment by will-gant** [comment]
Ok, I seem to have fixed it by fiddling around. You may have been right, but if I did merge them I'm not quite sure how (!).

Also not sure which of the things I just did made this work for me, but the file is now showing the correct contents when I view it locally. Thanks!

![screenshot 2017-03-17 at 11 29 02](https://cloud.githubusercontent.com/assets/20523607/24039343/15b1dfec-0b05-11e7-81ba-1e62255504e2.png)

**Comment by FiddlersCode** [comment]
I am having the same problem!!

**Comment by ffasolin** [comment]
Have you tried pulling the branch from github like Will has? I think you could also checkout the commit before you merged the branches - if that is your issue.

**Comment by FiddlersCode** [comment]
Actually, the issue I had was a bit different and I think I've sorted it.
