### ISSUE TITLE
Week 3 Exercise 8:8 Trying to print out the students grouped by their cohort

### ISSUE THREAD

**Issue by funmia** [makersacademy/problem-solving#83]
Hello, I am working on exercise 8:8 of the student directory. I haven't figured out an efficient way to print out the students based on their cohorts. Please, can you share your approach to the problem, Thank you :)
This is the code I'm using & what I have so far;
![test](https://user-images.githubusercontent.com/22508999/27451493-1779c0c8-5787-11e7-9cbe-1a84bb6f08ad.PNG)

``` #I have my students array 
students = [
  {name: "Dr. Hannibal Lecter", cohort: :november},
  {name: "Darth Vader", cohort: :november},
  {name: "Nurse Ratched", cohort: :october},
  {name: "Michael Corleone", cohort: :january},
  {name: "Alex DeLarge", cohort: :november},
  {name: "The Wicked Witch of the West", cohort: :october},
  {name: "Terminator", cohort: :november},
  {name: "Freddy Krueger", cohort: :january},
  {name: "The Joker", cohort: :october},
  {name: "Joffrey Baratheon", cohort: :november},
  {name: "Norman Bates", cohort: :november}
]

#Here I use map to store all the cohort values 
cohorts = students.map { |student| student[:cohort] }

#Then I'm trying to print them grouped by cohorts but  currently using a hard-coded index position that chooses ":november"

result = []
i = 0
puts " Here are the students from the #{cohorts[0]} cohort"
while i < students.size 
   if cohorts[0] == students[i][:cohort]
     result << students[i]
   end 
 i += 1 
end 

result  ```

**Comment by ghost** [comment]
@funmia try this:

```ruby
students = [
  {name: "Dr. Hannibal Lecter", cohort: :november},
  {name: "Darth Vader", cohort: :november},
  {name: "Nurse Ratched", cohort: :october},
  {name: "Michael Corleone", cohort: :january},
  {name: "Alex DeLarge", cohort: :november},
  {name: "The Wicked Witch of the West", cohort: :october},
  {name: "Terminator", cohort: :november},
  {name: "Freddy Krueger", cohort: :january},
  {name: "The Joker", cohort: :october},
  {name: "Joffrey Baratheon", cohort: :november},
  {name: "Norman Bates", cohort: :november}
]

#Here I use map to store all the cohort values 
cohorts = students.map { |student| student[:cohort] }
 
#Then I'm trying to print them grouped by cohorts but  currently using a hard-coded index position that chooses ":november"

result = []
i = 0
puts " Here are the students from the #{cohorts[0]} cohort"
while i < students.size 
   if cohorts[0] == students[i][:cohort]
     result << students[i][:name] #=> 1
   end 
 i += 1 
end 

puts result 
```

1 #=> once you reached a match (cohort is november) then output the name of that student


result << students[i]  #=> this is part of your original code... once you reach a match, doing students[i] outputs the whole hash, but you want only the name (the key name). 
Therefore: 
```ruby
students[i][:name]
```

**Comment by funmia** [comment]
@AlexSusanu Thank you. What I meant was printing my entire list of students but grouping them by cohorts? 
Following the instruction in exercise 8:8? Maybe I'm misinterpreting the instruction?
 ` Once you complete the previous exercise, change the way the users are displayed: print them grouped by cohorts. To do this, you'll need to get a list of all existing cohorts (the map() method may be useful but it's not the only option), iterate over it and only print the students from that cohort.`

**Comment by jransome** [comment]
You can use the sort_by! method on the students array to sort them by cohort, like this:
`students.sort_by! {|student| student[:cohort] }`

**Comment by funmia** [comment]
@jransome  Thank you, that works! :)

**Comment by oleglukyanov** [comment]
I thought that it could be handy to sort students by cohorts in a calendar order. So January students would be printed before April ones.

To do so I created an array of all cohorts in their calendar order outside of all methods:
`COHORTS = [:january, :february, :march, :april, :may, :june, :july, :august, :september, :october, :november, :december]`

And then iterated through this array. On each iteration printing only the students whose cohort matches the current one, like this:
```
def print_students_list
  return if STUDENTS.empty?
  i = 1
  COHORTS.each { |cohort|
    STUDENTS.each { |student|
      if student[:cohort] == cohort
        print_student(student, i)
        i += 1
      end
    }
  }
end
```

Still need that ugly index `i` because I wanted a numbered list so lines would have numbers according to the printing order not students' indices in the array.

**Comment by funmia** [comment]
@oleglukyanov Thanks for sharing this! I'll give it a try :) 👍

**Comment by aballal** [comment]
@oleglukyanov - I had the same thought. But did it this way:

```
COHORT_LIST = [:january,:february,:march,:april,:may,:june,:july,:august,:september,:october,:november,:december]

students = students.sort_by {|student| COHORT_LIST.index(student[:cohort])}

```
'students' then gets passed on to the same generic print function. sort_by! should work too instead of sort_by.

**Comment by oleglukyanov** [comment]
@aballal - that's much more elegant indeed!
Thanks for sharing ;-)
