### ISSUE TITLE
step 11 clarification

### ISSUE THREAD

**Issue by kitkat119** [makersacademy/problem-solving#86]
When it says to add the .gitignore file to your project is it correct to use echo .gitignore >> directory.rb ??
As I did this and now the directory file won't run as it says it is expecting an end. 
I'm not sure how else you could add it to the file so wondered if anyone could clarify/correct me?!
Thanks and sorry if I'm just being a bit dim!

**Comment by artemisxen** [comment]
I think that what you need to do is to make the .gitignore file in the students-directory and inside it write the name of the file that you want to ignore (students.csv) using echo. Then, when you will use git status you will see the .gitignore file as well (but not the students.csv anymore) and you need to add the .gitignore file with the git add command.

**Comment by kitkat119** [comment]
Ohh so when it says "you'll need to add the .gitignore file itself to the project" it means add to github. I totally misinterpreted it as add it to your project directory.rb. I was being dim! Thank you for explaining :)

**Comment by artemisxen** [comment]
Yes, you need to add it to the github.
You are welcome :)
