### ISSUE TITLE
Kata: Without the letter 'E'

### ISSUE THREAD

**Issue by langphil** [makersacademy/problem-solving#89]
Anyone have any thoughts on why the following Kata is throwing an 'Undefined method error' but passing the tests. A tad stumped. 

[Kata link](https://www.codewars.com/kata/without-the-letter-e/train/ruby)

![screen shot 2017-06-27 at 15 49 33](https://user-images.githubusercontent.com/5029907/27593919-5b4fc2f8-5b50-11e7-96f0-16137a85f1c3.png)

**Comment by paulmillen** [comment]
Perhaps because s.class == NilClass, not nil?  Thus the nil case isn't accommodated?

edit: no, looking at it again, that's not answering your question.  I guess your method is failing as include? can't be used with nil but it's still returning a nil value thus satisfying the nil condition?

**Comment by tobold** [comment]
It's passing the first four tests, then failing the fifth because the code is trying to use the .include? method for Nil, and the Nil class doesn't include that method.

I think you can fix it by moving the 'return nil if' line to the top line so it's the first thing it checks for

**Comment by ghost** [comment]
@langphil try this:
```ruby
def find_e(s)
  return nil if s == nil
  return "" if s == ""
  return s.count("E" "e").to_s if s.include?("E")
  return 'There is no "e".' if !s.include?("E") && s.length > 0
end
```

**Comment by langphil** [comment]
All solved.

Thanks for the help!
'
def find_e(s)
  return nil if s == nil
  return s.count("E" "e").to_s if s.include?("E")
  return 'There is no "e".' if !s.include?("E") && s.length > 0
  return "" if s.empty?
end
`
