### ISSUE TITLE
Week3, Step 12/13: (NoMethodError) for to_sym method

### ISSUE THREAD

**Issue by memunyawiri** [makersacademy/problem-solving#90]
Hi all, 

I'm trying to run the program from week3, step 12 & 13 but I keep getting a NoMethodError for the to_sym in the load_students method. 

The things I've tried to resolve the issue or figure out how to:
- I've cross-checked my code with the code on teachable and it's identical
- I've also paired on it and my pair-up partner wasn't receiving any errors and has the same code 
- I also checked if the method "to_sym" is available on the version of Ruby I have installed via "-ve" in the command line and it is
- I ran a syntax and warnings check via "-cw" in the command line and nothing is wrong according to that
- I've googled the issue and have tried the one relevant solution I could find (spell-check) and there's nothing there either

Below is a screenshot of the method and a screenshot of the error I keep getting.
Any ideas or solutions would be greatly appreciated.

![screen shot 2017-06-27 at 16 28 00](https://user-images.githubusercontent.com/20502799/27595812-9faa6174-5b55-11e7-8506-5d80bc35f3d6.png)

![screen shot 2017-06-27 at 16 25 54](https://user-images.githubusercontent.com/20502799/27595713-5f52c670-5b55-11e7-9ea6-d1d6f703bb5a.png)

**Comment by tobold** [comment]
Only thing I can think of is that your students.csv file might be is empty, whereas your pairing partner's file wasn't empty? If not I'm stumped.

**Comment by aballal** [comment]
When you ask for user input, any field that is optional or doesn't have a default value has the possibility of being blank. This means when it is written to the file during save it will have no data. Subsequently, when it is read from the file in load method it will be read as nil. This can end up throwing lots of exceptions. For instance at .to_sym here or .empty? if you were using it anywhere in your code etc. To make sure your code doesn't break, for any field that is optional or doesn't have a default value, while loading after reading from file and while inserting into array do a .to_s and then do whatever you need. In this instance it will be .to_s.to_sym.

Having blank data for an optional field is valid input which means the code should be able to cater to it and not throw the NilClass exception.

I hope this helps.

**Comment by memunyawiri** [comment]
@tobold the file wasn't empty, thanks though!
@aballal that worked! Thanks so much :)

**Comment by aballal** [comment]
That's great. Though the file wasn't empty @tobold 's reasoning still holds because the field was empty.

**Comment by memunyawiri** [comment]
@aballal @tobold  ahh I see, thank you both for your help!
