### ISSUE TITLE
Nested loop optimisation

### ISSUE THREAD

**Issue by paulmillen** [makersacademy/problem-solving#91]
The below solves [this](https://www.codewars.com/kata/554f76dca89983cc400000bb/train/ruby) Codewars kata but it takes too long!  Does anyone have any ideas how I could make it more efficient?  I don't want to just reveal the solution...

```
def sol_equa(n)
  to_return = []
    (0..n).each do |x|
      (0..n).each do |y|
    (x-2*y)*(x+2*y) == n ? to_return << [x,y] : next
      end
    end
    to_return
end
```

**Comment by oleglukyanov** [comment]
Nice kata indeed.
I don't have an answer yet but wanted to share a few initial thoughts.
From what I found so far, your solution can be written like this:

```
def sol_equa(n)
  to_return = []
  Array(0..n).repeated_permutation(2).each do |x, y|
    to_return << [x,y] if (x-2*y)*(x+2*y) == n
  end
  to_return.sort_by! { n[0] }.reverse
end
```

But it's no more efficient than nested loops in terms of time spent.

I also tried reducing the ranges for x and y to the effective ones:

```
def sol_equa(n)
  to_return = []
  (0..n * 3 / 4).each do |x|
    (0..x / 2).each do |y|
       to_return << [x,y] if (x-2*y)*(x+2*y) == n
    end
  end
    to_return.sort_by! { n[0] }.reverse
end
```

This shaves few more seconds off but still not enough to pass everything.
May be it needs another strategy...

**Comment by paulmillen** [comment]
Thanks for your thoughts!  Man - I really can't think of a way around it other than nested loops.  I played around a bit with .permutation methods but couldn't find anything satisfactory.  Real head scratcher...

**Comment by oleglukyanov** [comment]
I'm a bit puzzled too.

One more thought, on the rights of brainstorming it: they give us a hint that the left part can be expanded as `(x-2*y)*(x+2*y)` which hint we didn't use. So both `x-2*y` and `x+2*y` must be integers and factors of n. 

This could give us a shorter list of x and y's to iterate through.

**Comment by oleglukyanov** [comment]
This may be a bit of a clue: https://gist.github.com/spren9er/fc0e7bbf0195d62c21c0

**Comment by paulmillen** [comment]
Well, I caved and revealed the solutions.   This is the most compact.  Spoilers below...

```
def sol_equa(n)
  (1..n**0.5).map{|a, arr|
    b = n/a
    [(b + a)/2, (b - a)/4] if a*b == n and (b-a) % 4 == 0
  }.compact
end
```
So simple!  If only I was more mathematically minded...

**Comment by oleglukyanov** [comment]
do you understand what that 'arr' in pipes does? Seems to be an unused argument...

**Comment by paulmillen** [comment]
No idea - it does seem to be superfluous.
