### ISSUE TITLE
Problem running rspec in fizzbuzz challenge

### ISSUE THREAD

**Issue by kitkat119** [makersacademy/problem-solving#92]
I have followed the instructions for setting up the fizzbuzz challenge but when I try to run rspec, I get the following message. Any ideas what is going on and how I can make it work?
Thanks!

dowkr14:~/workspace/Projects/fizzbuzz (master) $ rspec fizzbuzz_spec.rb
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x5cba84 rspec-support-3.6.0> (NoMethodError)
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations.rb:1:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:743:in `block in expect_with'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:738:in `map'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:738:in `expect_with'
        from /home/ubuntu/workspace/Projects/fizzbuzz/spec/spec_helper.rb:20:in `block in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core.rb:98:in `configure'
        from /home/ubuntu/workspace/Projects/fizzbuzz/spec/spec_helper.rb:16:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `block in requires='
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `requires='
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:111:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:21:in `configure'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:99:in `setup'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.6.0/exe/rspec:4:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/rspec:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/rspec:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by ghost** [comment]
@kitkat119 try this but please read the discussion from the link below before to make sure its same as your situation. it seems so, but just in case

https://github.com/rubygems/rubygems/issues/1420#issuecomment-256350006

https://stackoverflow.com/questions/35327947/engineyard-gem-failing-to-run-find-active-stub-by-path-reports-undefined-method

```
gem update --system
```

**Comment by kitkat119** [comment]
@AlexSusanu Thankyou so much for your help, that seems to have worked!
