### ISSUE TITLE
"cat >" command permission denied 

### ISSUE THREAD

**Issue by Samellenrider** [makersacademy/problem-solving#95]
Hi everyone, I'm working on lesson 13 of the precourse, but there is a hurdle. 
I tried to create a short text document in the browser with the "cat >" command, but the permission is denied.
Permission denied popped up bevor but I managed to get around it with the new "sudo" command.
I tried it here aswell but it won't work.
I added a screenshot below.
Thank you.
![fullsizeoutput_13](https://user-images.githubusercontent.com/29458215/27861837-c4c4845c-6182-11e7-8039-0298fe2166b7.jpeg)

**Comment by manoadamro** [comment]
as far as i understand, you are not calling cat on any file, you are just defining an output.
cat /path/to/file/ > path/to/output
or just
cat path/to/file 
to print it in the terminal

**Comment by Samellenrider** [comment]
I managed to get around it by changing the access rights of the file. 
Thank you for the help!

**Comment by manoadamro** [comment]
im still figuring cat out myself. glad you got it sorted!

**Comment by ofrost617** [comment]
Bit late to this but I was going to suggest looking at the permissions and adding to them if needs be. Glad you got it sorted!

**Comment by Samellenrider** [comment]
Thank you guy 👍
