### ISSUE TITLE
clmystery Step6 grep with |

### ISSUE THREAD

**Issue by ofrost617** [makersacademy/problem-solving#97]
Hey guys, I'm trying to use grep with flags to search for a keyword and a number of lines above and below then redirect this output using the pipe operator to grep for another keyword, but each time I try to do it it it doesn't redirect the output of the first grep to the next and I've tried so many combinations of code (see below) and each time I end up with the last keyword being returned but without the filter of the first keyword.

The below returns 2 lines above and below the vehicle colour and only returns for Blue as expected
`grep -C 2 Blue vehicles

License Plate A2W8QL0
Make: Jaguar
Color: Blue
Owner: Daniele Nurmukhambetova
Height: 6'2"`

As soon as I add a pipe operator, it's as if my first grep is ignored:
`grep -C 2 Blue vehicles | grep -C 2 Honda vehicles

License Plate QOBSFKL
Make: Honda
Color: Blue
Owner: Aurelie Kirkham
--
--

License Plate Z4FCH97
Make: Honda
Color: Green
Owner: Christian Brata`

and this continues for extra pipe operators I want to add in to search for L337 and 6'.

I've tried with and without leaving a space between | and words, no change.

Trying grep -E 'Blue|Honda|L337' vehicles gives a long list of each match but nothing above or below (due to not using -C N) and it's still not clear whether or not it's redirecting the output to the next search term. 

I'm going a bit crazy now, any help would be massively appreciated!

**Comment by stephengeller** [comment]
Hey! So when you use the grep command, I think adding 'vehicles' to the end of each one means it restarts the search through that file, instead of taking the output from the previous line before the pipe. If you try using 'cat filename | grep -C n searchword | grep -C n nextsearchword' without vehicles at the end of each one it should filter through alright without doing a new search through vehicles. Does that help?

**Comment by ofrost617** [comment]
That's done it straight away thank you!! Yeah that all makes total sense when you realise it, thanks :)

**Comment by stephengeller** [comment]
Great! No worries :)
