### ISSUE TITLE
ruby-kickstart, rake test issue on Cloud 9

### ISSUE THREAD

**Issue by david-div** [makersacademy/problem-solving#99]
Hi guys,

I'm making my way through the ruby-kickstart challenges, but I'm unable to run the rake tests (e.g. rake 1:1) in the terminal (on cloud 9)

I'm getting the following error:

daviddiv:~/workspace/makers/pre-course/week2/ruby-kickstart (master) $ rake 1:1
rake aborted!
Gem::LoadError: Could not find 'rspec' (~> 3.0) among 72 total gem(s)
Checked in 'GEM_PATH=/usr/local/rvm/gems/ruby-2.3.0:/usr/local/rvm/gems/ruby-2.3.0@global', execute `gem env` for more information
/home/ubuntu/workspace/makers/pre-course/week2/ruby-kickstart/Rakefile:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

Has anyone got the same issue/found a way around it?

Thanks

**Comment by rolandosorbelli** [comment]
Hi David,

in Cloud9 you can install the rspec 3.0 by typing:
`gem install rspec -v 3.0`

After that for sure it will give you something like that:
```
Could not find proper version of rspec-core (3.1.7) in any of the sources
Run `bundle install` to install missing gems.
```

So you can run:
```
bundle install
rspec-core
```

After this rake should work. Let me know if it doesn't.

**Comment by david-div** [comment]
I didn't even try to install anything, as I didn't think I'd have permission on cloud 9. Just installed the bundle and the first one seems to work fine!!! (now to check the rest of my code...)

Thanks :-D
